ASoC: Intel: Make glk+rt5682 echo ref dynamic
thesofproject/linux pull request #1907
Opened 2020-03-18 19:01 UTC by cujomalainey

Fixes #1793

2020-03-18 19:10 UTC, ranj063 submitted a review, later dismissed

2020-03-18 19:23 UTC, plbossart requested changes

2020-03-18 19:23 UTC, plbossart commented on sound/soc/intel/boards/glk_rt5682_max98357a.c
> +		.dynamic = 1,
The commit message is a bit misleading. It's more like this is required for SOF to ignore hard-coded front-ends signalled with the .dynamic field

2020-03-19 05:59 UTC, ranj063 approved these changes

2020-03-19 09:44 UTC, kv2019i commented
SOFCI TEST

2020-03-19 09:44 UTC, kv2019i approved these changes
Thanks, looks good! I'll try to kick the CI again to get at least one set of test results before merging.

2020-03-19 12:32 UTC, kv2019i commented
OK, tests are good as well. I'll give @plbossart a chance to ack his comments, but then this is ready for merge.

2020-03-19 14:40 UTC, plbossart approved these changes

2020-03-19 14:40 UTC, merged