.travis.yaml: bump image to Ubuntu 20.04 focal
thesofproject/linux pull request #2402
Opened 2020-08-28 06:45 UTC by xiulipan

Ubuntu 18.04 bionic is history
Remove the ppa for gcc tools as the default gcc version now
is GCC 9.3

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

2020-08-28 14:20 UTC, kv2019i requested changes
Otherwise looks good but clang build seems to fail:

```
Compiler lacks asm-goto support.

make: *** [arch/x86/Makefile:284: checkbin] Error 1

The command "make CC=clang ARCH=x86_64" exited with 2.
```

2020-08-28 15:19 UTC, marc-hb commented
> Ubuntu 18.04 bionic is history

It's not that old, do we really want to stop supporting it, even when it seems to still be compiling everything fine? I think @libinyang  has been spending a lot of effort backporting ALSA packages to it.

2020-08-28 18:38 UTC, plbossart commented
One step at a time please

A) fix PPA issue (send PR #2406)
B) fix makefile options (PR #2405)
C) fix Clang (errors + you are missing the parallel compilation added in B - was part of make.cross)
D) change to focal. I think we need to ditch 18.04 for development, no one should be using it in the SOF teams.

2020-08-28 19:55 UTC, marc-hb commented
> D) change to focal. I think we need to ditch 18.04 for development, 

Not sure what you mean by "for development", what else is there besides "development"? 

So was @libinyang 's 18.04 work in #2211 just a waste of time?

BTW sof-docs still refer to 16.04 and to 18.04 but not to 20.04 yet
https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html#step-1-set-up-build-environment

There's evidence of some developer(s) still using 16.04: https://github.com/thesofproject/sof/pull/3166#issuecomment-665602977 (cc: @mrajwa , @jajanusz  )

which is surprising considering the recent ALSA dependencies for UUID https://github.com/thesofproject/sof/pull/2919

> no one should be using it in the SOF teams.

Most (but not all) developers tend to use the latest and greatest, which is why it is useful to keep CI on the oldest _and_ supported versions.

2020-08-28 20:03 UTC, plbossart commented
> Most (but not all) developers tend to use the latest and greatest, which is why it is useful to keep CI on the oldest _and_ supported versions.

It took me 3 months to ask that all CI target devices use 20.04, I don't want a repeat here. 
Everyone uses 20.04, period. SOF CI also uses 20.04. If there is a compilation bug with another setup, kbuild will tell us.

And yes I don't care about alsa-lib for 18.04, this is completely useless. The ask was on 20.04 so that we can test on CI/test devices.

2020-08-31 01:47 UTC, libinyang commented
> 
> So was @libinyang 's 18.04 work in #2211 just a waste of time?
> 
@marc-hb I didn't work on 18.04 now. Our CI has already moved to 20.04. Please refer the patches for alsa-lib and pulseaudio in gitlab and the jenkins job of build_userspace_package. They are for 20.04.

2020-08-31 08:34 UTC, xiulipan commented
@kv2019i @plbossart I will close this PR as I see most task is already done.

2020-08-31 08:34 UTC, closed without merging