ASoC: SOF: fix unused variable declaration
thesofproject/linux pull request #2428
Opened 2020-09-11 19:46 UTC by cujomalainey

codec isn't used if SND_SOC_SOF_HDA_AUDIO_CODEC is not enabled which
results in build failures in certain configurations

Fixes: 89d73ccab20a ("ASoC: SOF: Intel: hda: fix generic hda codec support")
Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>

2020-09-11 19:50 UTC, plbossart approved these changes

2020-09-11 20:50 UTC, cujomalainey commented
travis failure is a unrelated checkpatch script glitch

2020-09-11 21:32 UTC, ranj063 approved these changes

2020-09-14 01:11 UTC, bardliao approved these changes

2020-09-14 05:09 UTC, dbaluta approved these changes

2020-09-14 10:06 UTC, kv2019i commented
Weird, I tried to merge, but merging fails with no error in web UI...

2020-09-14 10:54 UTC, kv2019i requested changes
Ok, took a while to figure out, but this fix is identical to one Pierre did upstream and what we recently merged:
```
commit 2e3e0bc378f205370fc4c6dbd9374d66e803ce53
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date:   Thu Aug 13 12:58:36 2020 -0500

    ASoC: SOF: Intel: hda-codec: move variable used conditionally
```

This will lead to error in rebasing, but for some reason github did not report this in the UI as a rebase faillure.

2020-09-14 13:06 UTC, kv2019i commented
@cujomalainey Ok to close?

2020-09-14 14:56 UTC, plbossart commented
> Ok, took a while to figure out, but this fix is identical to one Pierre did upstream and what we recently merged:
> 
> ```
> commit 2e3e0bc378f205370fc4c6dbd9374d66e803ce53
> Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
> Date:   Thu Aug 13 12:58:36 2020 -0500
> 
>     ASoC: SOF: Intel: hda-codec: move variable used conditionally
> ```
> 
> This will lead to error in rebasing, but for some reason github did not report this in the UI as a rebase faillure.

Ah yes. I really thought this looked similar to an existing fix but I didn't remember it was mine... thanks @kv2019i for tracking this.

2020-09-14 16:35 UTC, cujomalainey commented
Ah thanks for spotting, when I checked marks tree last week it wasn't there. Yea let's close

2020-09-14 16:35 UTC, closed without merging