ASoC: Intel: add support for Dell Olympic MLK
thesofproject/linux pull request #2429
Opened 2020-09-14 05:53 UTC by bardliao

The codecs use different sdw links from CML version. Adding codecs
information to support them.

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

2020-09-14 13:29 UTC, kv2019i submitted a review, later dismissed
I'm a bit put off that so many lines need to be touched to support a different SKU, but that's really not a question of this patch and the code changes look ok.

2020-09-14 13:29 UTC, kv2019i commented on sound/soc/intel/common/soc-acpi-intel-tgl-match.c
> +		.link_mask = 0x7,
Minor note for future: given we use BIT(x) macro in these structs, would seem more aligned to use GENMASK() to define the masks ... i.e. GENMASK(3,0) instead of 0x7

2020-09-14 15:01 UTC, plbossart requested changes
please remove code names...

2020-09-14 15:01 UTC, plbossart commented on sound/soc/intel/common/soc-acpi-intel-tgl-match.c
> +static const struct snd_soc_acpi_link_adr tgl_olympic_mlk[] = {
please remove references to 'olympic mlk', we don't use such code names (including in the commit message)

We can call this tgl_sdw_rt711_link1_rt1308_link2_rt1715_link0.

2020-09-15 02:17 UTC, bardliao commented
> please remove code names...

Done

2020-09-15 05:37 UTC, bardliao commented
@plbossart @RanderWang Looking at the pr-device-test fail on CML_STRADALE_RT711. 
```
kernel: [    3.176993] sof_sdw sof_sdw: control 2:0:0:rt1308-1 RX Channel Select:0 is already present
kernel: [    3.177019] rt1308 sdw:2:25d:1308:0: ASoC: Failed to add RX Channel Select: -16
```
The existing code is
```
	/* rt1308 left on link 1 */
	{
		.dlc = COMP_CODEC_CONF("sdw:1:25d:1308:0"),
		.name_prefix = "rt1308-1",
	},
	/* rt1308 right on link 2 */
	{
		.dlc = COMP_CODEC_CONF("sdw:2:25d:1308:0"),
		.name_prefix = "rt1308-2",
	},
```
And it will conflict with 
```
	/* rt1308 on link 2 */
	{
		.dlc = COMP_CODEC_CONF("sdw:2:25d:1308:0"),
		.name_prefix = "rt1308-1",
	},
```
The point is that ``COMP_CODEC_CONF("sdw:2:25d:1308:0"),`` is ``rt1308-1`` on one device but is ``rt1308-2`` on the other device.
What should we do in your opinion?

2020-09-15 08:33 UTC, RanderWang commented
> @plbossart @RanderWang Looking at the pr-device-test fail on CML_STRADALE_RT711.
> 
> ```
> kernel: [    3.176993] sof_sdw sof_sdw: control 2:0:0:rt1308-1 RX Channel Select:0 is already present
> kernel: [    3.177019] rt1308 sdw:2:25d:1308:0: ASoC: Failed to add RX Channel Select: -16
> ```
> 
> The existing code is
> 
> ```
> 	/* rt1308 left on link 1 */
> 	{
> 		.dlc = COMP_CODEC_CONF("sdw:1:25d:1308:0"),
> 		.name_prefix = "rt1308-1",
> 	},
> 	/* rt1308 right on link 2 */
> 	{
> 		.dlc = COMP_CODEC_CONF("sdw:2:25d:1308:0"),
> 		.name_prefix = "rt1308-2",
> 	},
> ```
> 
> And it will conflict with
> 
> ```
> 	/* rt1308 on link 2 */
> 	{
> 		.dlc = COMP_CODEC_CONF("sdw:2:25d:1308:0"),
> 		.name_prefix = "rt1308-1",
> 	},
> ```
> 
> The point is that `COMP_CODEC_CONF("sdw:2:25d:1308:0"),` is `rt1308-1` on one device but is `rt1308-2` on the other device.
> What should we do in your opinion?

Can we add platform info in name_prefix ? "rt1308MLK-1"

2020-09-15 09:01 UTC, bardliao commented
> Can we add platform info in name_prefix ? "rt1308MLK-1"

Yes, we can do that, but we will need to modify [rt1308_map[]](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_sdw_rt1308.c#L27) as well if we use different prefix here.

2020-09-15 14:23 UTC, plbossart commented
This CODEC_CONF is not so good, it duplicates what is done already in the acpi machine table.
Maybe we should move the prefix in acpi machine table and revisit all this.

2020-09-15 19:14 UTC, plbossart commented
@bardliao @RanderWang please see PR #2438 for a suggestion on the handling of codec name prefix.

2020-09-16 18:55 UTC, plbossart commented
@bardliao I'll close this since we have PR #2438 that's more generic

2020-09-16 18:55 UTC, closed without merging