fixup! ASOC: Intel: sof_sdw: restore playback functionality with max9…
thesofproject/linux pull request #2449
Opened 2020-09-18 03:27 UTC by bardliao

…8373 amps

 'ret' might be used uninitialized in max98373_sdw_trigger().

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

2020-09-18 05:24 UTC, keqiaozhang commented
Confirmed that this PR can fix the KW warning.

2020-09-18 06:28 UTC, lyakh approved these changes

2020-09-18 06:30 UTC, lyakh commented
...assuming we really want to return an error in case of `SNDRV_PCM_TRIGGER_DRAIN`?

2020-09-18 08:24 UTC, RanderWang approved these changes
thanks!

2020-09-18 08:27 UTC, RanderWang requested changes
we only take care these case, so default should be zero, ignore

2020-09-18 10:48 UTC, bardliao commented
> we only take care these cases, so default should be zero(ignore other cases)

But looking at [sof_sdw.c](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_sdw.c#L277). It return -EINVAL in the default case. And it is consistent to other ALSA drivers.

2020-09-18 14:44 UTC, plbossart commented
right, we don't support DRAIN at the moment so there's no point in trying to ignore it. Quite the contrary, if we end-up enabling DRAIN, it's useful if we get errors so that we have a clear list of everything that needs to be fixed.

2020-09-18 14:45 UTC, plbossart approved these changes

2020-09-21 03:44 UTC, RanderWang approved these changes
follow all trigger functions in SOF. LGTM

2020-09-21 05:58 UTC, merged