fixup! ASoC: rt715-sdca: First version of rt715 sdw sdca codec driver
thesofproject/linux pull request #2527
Opened 2020-10-23 07:26 UTC by jack-cy-yu

Add rt715_sdca prefix for all non-static symbols.

Signed-off-by: Jack Yu <jack.yu@realtek.com>

2020-10-23 09:09 UTC, RanderWang requested changes
you made two changes in your PR, one is adjusting function params to two lines. please seperate it to another PR. And do you mean static symbols in your commit message ?

2020-10-28 19:11 UTC, plbossart commented
> you made two changes in your PR, one is adjusting function params to two lines. please seperate it to another PR. And do you mean static symbols in your commit message ?

we don't really care @RanderWang, this is a fixup that's going to be squashed.

2020-10-28 19:11 UTC, plbossart approved these changes

2020-10-29 02:59 UTC, bardliao approved these changes

2020-10-29 05:19 UTC, RanderWang approved these changes

2020-10-29 14:12 UTC, merged