fixup! ASoC: rt715-sdca: First version of rt715 sdw sdca codec driver
thesofproject/linux pull request #2558
Opened 2020-11-09 09:18 UTC by jack-cy-yu

Merge multiple mute/volume operation into single mute/volume operation
to fit sdca topology.

Signed-off-by: Jack Yu <jack.yu@realtek.com>

2020-11-09 14:04 UTC, lyakh requested changes

2020-11-09 14:04 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +	int ret, i;
any particular reason why `loop_cnt` is unsigned and `i` is signed? I don't see any reason for `i` to be negative, and since you use `i` as a loop index to compare against `loop_cnt`, it's better to have them with the same signedness

2020-11-09 14:04 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +	for (i = 0 ; i < loop_cnt; i++) {
superfluous space before the first `;`

2020-11-09 14:04 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +int rt715_sdca_get_volsw(struct snd_kcontrol *kcontrol,
`static`

2020-11-09 14:04 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +			max - ucontrol->value.integer.value[0];
how about
```
ucontrol->value.integer.value[0] = invert ? max - val : val;
```

2020-11-09 14:04 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +			max - ucontrol->value.integer.value[1];
ditto, and you don't need a second `val2` variable

2020-11-09 14:04 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +	val = snd_soc_component_read(component, reg);
I'd actually just use `mc->reg` and `mc->rreg` in these calls directly - would look easier IMHO. Is it common to ignore possible failures of these calls?

2020-11-09 14:04 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +int rt715_sdca_put_volsw(struct snd_kcontrol *kcontrol,
`static`

2020-11-09 14:04 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +	return err;
`return 0;`

2020-11-11 07:38 UTC, lyakh requested changes

2020-11-11 07:38 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +	for (i = 0 ; i < loop_cnt ; i++) {
no, sorry, I didn't mean *missing* spaces, I meant *superfluous* spaces. It should be
```
for (i = 0; i < loop_cnt; i++) {
```
i.e. *no* space before the 2 semicolons

2020-11-11 07:38 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +	for (i = 0 ; i < loop_cnt ; i++) {
ditto, remove spaces *before* semicolons

2020-11-11 07:38 UTC, lyakh commented on sound/soc/codecs/rt715-sdca.c
> +	unsigned int val = 0, val2 = 0, loop_cnt = 2, i;
superfluous initialisations of `val` and `val2`. They will be unconditionally assigned within the first 5 lines of the function, please, remove.

2020-11-11 11:48 UTC, RanderWang commented on sound/soc/codecs/rt715-sdca.c
> +		reg = (i == 3) ? (mc->rreg - 2) | BIT(15) : mc->rreg + i * 2;
how about change it  to 
````C
reg = (i == 3) ? (mc->rreg - 2) | BIT(15) : mc->rreg + i * 2;
ret = regmap_write(rt715->mbq_regmap, reg, gain_r_val);
````

2020-11-11 11:51 UTC, RanderWang commented on sound/soc/codecs/rt715-sdca.c
> +	unsigned int invert = mc->invert;
I prefer this shape
````C
unsigned int invert = mc->invert;
int max = mc->max;
````

2020-11-11 11:53 UTC, RanderWang commented on sound/soc/codecs/rt715-sdca.c
> +	int max = mc->max;
also refine declaration to shape like
aaaaaaa
aaaaa
aaa
a

2020-11-11 17:22 UTC, plbossart commented
I am still trying to figure out what the best way to support SDCA Feature Units is, please give me a couple of days for reviews. thanks @jack-cy-yu

2020-11-12 06:58 UTC, RanderWang approved these changes
LGTM

2020-11-12 07:02 UTC, lyakh approved these changes
a formal approval to neutralise my requests for changes, thanks for addressing the comments!

2020-11-23 05:02 UTC, bardliao commented
The BSW_CYN_MAX98090:kernel boot fail should not related to this PR and the Travis CI build failed is just alignment issue which is acceptable. So merge it now.

2020-11-23 05:02 UTC, merged

2020-11-23 05:56 UTC, bardliao commented
@libinyang @plbossart The control name has been changed. UCM change is required.