Revise sdw use no pm patches
thesofproject/linux pull request #2607
Opened 2020-12-07 11:31 UTC by bardliao

Address commits from maintainers. 
1. Remove fixed tags
2. Separate commits
No code changed.

2020-12-07 16:06 UTC, plbossart requested changes
last patch commit subject is misleading.

Also check with Vinod Koul if he really meant removing all the fixes tag, we want these changes back-ported to 5.10.

2020-12-07 16:06 UTC, plbossart commented on drivers/base/regmap/regmap-sdw-mbq.c
> +MODULE_LICENSE("GPL");
the commit message could be misleading. We are not changing the license at all.

use MODULE_LICENSE("GPL")

also add a pointer to the licensing rules for reference.

2020-12-08 03:37 UTC, bardliao commented
> last patch commit subject is misleading.
> 
> Also check with Vinod Koul if he really meant removing all the fixes tag, we want these changes back-ported to 5.10.

I saw you have replied Vinod, so I will wait for his reply. BTW, we can't partially back-port these changes, right?

2020-12-08 03:44 UTC, plbossart commented
> > last patch commit subject is misleading.
> > Also check with Vinod Koul if he really meant removing all the fixes tag, we want these changes back-ported to 5.10.
> 
> I saw you have replied Vinod, so I will wait for his reply. BTW, we can't partially back-port these changes, right?

I don't know what you mean by 'partially back-port these changes'? We need all of these, if you cherry-pick then 5.11 will not work at all.

2020-12-08 05:35 UTC, bardliao commented
> > > last patch commit subject is misleading.
> > > Also check with Vinod Koul if he really meant removing all the fixes tag, we want these changes back-ported to 5.10.
> > 
> > 
> > I saw you have replied Vinod, so I will wait for his reply. BTW, we can't partially back-port these changes, right?
> 
> I don't know what you mean by 'partially back-port these changes'? We need all of these, if you cherry-pick then 5.10 w/ some but not all fixes will not work at all.

Yes, that answered my question. I meant removing some fixes tags and only cherry-picking those with fixes tags to 5.10 will not work.

2020-12-08 11:18 UTC, bardliao commented
@plbossart Vinod agree that we put fixes flags. I put them back. And I added below for the ``soundwire: export sdw_write/read_no_pm functions`` commit.
Fixes: 0231453 ('soundwire: bus: add clock stop helpers')
Fixes: 60ee9be ('soundwire: bus: add PM/no-PM versions of read/write functions')
Could you review it?

2020-12-08 15:28 UTC, plbossart requested changes
two minor cosmetic problems, looks good otherwise.

2020-12-08 15:28 UTC, plbossart commented on drivers/base/regmap/regmap-sdw-mbq.c
> +MODULE_LICENSE("GPL");
typo in commit message: "the same".

2020-12-08 15:28 UTC, plbossart commented on drivers/soundwire/bus.c
> +int
single line?

2020-12-09 00:59 UTC, bardliao commented on drivers/soundwire/bus.c
> +int
updated

2020-12-09 01:00 UTC, bardliao commented on drivers/base/regmap/regmap-sdw-mbq.c
> +MODULE_LICENSE("GPL");
updated

2020-12-09 01:25 UTC, plbossart approved these changes
Sounds good @bardliao

2020-12-09 01:55 UTC, RanderWang approved these changes
only one line code change with 16 commit :)

2020-12-09 02:41 UTC, merged