Revert fwnode changes and add description of fwnode cases
thesofproject/linux pull request #2655
Opened 2020-12-23 05:15 UTC by bardliao

There are only four valid fwnode cases which are
- primary->secondary->-ENODEV
- primary->NULL
- secondary->-ENODEV
- NULL

dev->fwnode should be converted between the 4 cases above no matter
how/when set_primary_fwnode() and set_secondary_fwnode() are called.
Describe it in the code so people will keep it in mind.

2020-12-23 05:16 UTC, bardliao commented
@andy-shev Could you review this PR?

2020-12-23 18:34 UTC, andy-shev requested changes
Commit message is unclear. Can you rephrase it, like "While the commit SHA ("DESCRIPTION") describes everything correct in its commit message the change it made does the opposite and original commit SHA ("DESCRIPTION") was fully correct. Thus, revert the former one here and improve documentation in the next patch". Also it misses Fixes tag.

2020-12-23 18:36 UTC, andy-shev requested changes
add spaces and one dash in the list, so it will be ' --> ' to avoid potential confusion with C pointers.

2020-12-24 01:50 UTC, bardliao commented
Thanks @andy-shev PR updated.

2020-12-24 08:05 UTC, lyakh commented on drivers/base/core.c
> +				fn->secondary = NULL;
I think by "original commit SHA ("DESCRIPTION") was fully correct" something different was meant, I think @andy-shev was asking to mention the original commit that introduced the code before https://github.com/thesofproject/linux/commit/d5dcce0c414fcbfe4c2037b66ac69ea5f9b3f75c

2020-12-24 12:14 UTC, bardliao commented on drivers/base/core.c
> +				fn->secondary = NULL;
> I think by "original commit SHA ("DESCRIPTION") was fully correct" something different was meant, I think @andy-shev was asking to mention the original commit that introduced the code before [d5dcce0](https://github.com/thesofproject/linux/commit/d5dcce0c414fcbfe4c2037b66ac69ea5f9b3f75c)

Thanks @lyakh for pointing it out.

2020-12-26 20:47 UTC, andy-shev commented
Last version looks good enough to me to be sent upstream.
Consult with Pierre and whoever else who approves this and proceed.

2020-12-28 00:08 UTC, bardliao commented
SOFCI TEST

2021-01-05 02:10 UTC, bardliao commented
@lyakh Does it look good to you?

2021-01-05 02:10 UTC, bardliao commented
SOFCI TEST

2021-01-05 06:47 UTC, lyakh approved these changes

2021-01-05 07:57 UTC, merged

2021-01-05 11:39 UTC, andy-shev commented
Can you send these upstream, please?

2021-01-06 01:45 UTC, bardliao commented
> Can you send these upstream, please?

Yes, done. And I saw your `Reviewed-by` tag. Thanks @andy-shev