power off iDisp link during D0i3
thesofproject/linux pull request #2731
Opened 2021-02-03 07:25 UTC by ranj063

2021-02-03 11:03 UTC, kv2019i requested changes
First patch looks ok now. I think the second patch is the right idea, but needs work on implementation. I also check if I can come up with a cleaner approach to this today.

2021-02-03 11:03 UTC, kv2019i commented on sound/pci/hda/hda_codec.c
> +	struct hdac_ext_link *hlink;
I think the idea is good, but we need to formalize hda_ext usage from codec code a bit better. This now assumes controller is using the ext interface, which does not hold true for the legacy driver.

2021-02-03 11:08 UTC, lyakh requested changes

2021-02-03 11:08 UTC, lyakh commented on sound/pci/hda/hda_codec.c
> +		snd_hdac_codec_link_down(&codec->core);
`link_up()`?

2021-02-03 13:33 UTC, kv2019i commented
@ranj063 I uploaded an alternative to the second patch:
https://github.com/thesofproject/linux/pull/2732

If you are ok, I can send as RFC to Takashi. This is first-ever extension of HDA extended core towards codec driver code, so this will warrant some extra review.

2021-02-03 15:24 UTC, kv2019i submitted a review, later dismissed

2021-02-03 19:17 UTC, plbossart approved these changes
LGTM, nice evolution from the initial code. Thanks @ranj063 and @kv2019i

2021-02-04 01:28 UTC, keyonjie reviewed
Hi @ranj063 @kv2019i @plbossart only one concern here, is our Audio IP designed to run iDisp link with D0i3 set? If so, maybe not wise to power down dsp link blindly here, otherwise, we might need revisit this part and back and forth change could happen.

2021-02-04 08:54 UTC, lyakh approved these changes

2021-02-04 14:57 UTC, plbossart commented
> Hi @ranj063 @kv2019i @plbossart only one concern here, is our Audio IP designed to run iDisp link with D0i3 set? If so, maybe not wise to power down dsp link blindly here, otherwise, we might need revisit this part and back and forth change could happen.

D0i3 is opt-in, we have to specify which streams/outputs are D0i3 compatible so we are in complete control here.

2021-02-04 15:30 UTC, keyonjie commented
> > Hi @ranj063 @kv2019i @plbossart only one concern here, is our Audio IP designed to run iDisp link with D0i3 set? If so, maybe not wise to power down dsp link blindly here, otherwise, we might need revisit this part and back and forth change could happen.
> 
> D0i3 is opt-in, we have to specify which streams/outputs are D0i3 compatible so we are in complete control here.

Imagine that if we want to run HDMI audio on D0i3 and specify d0i3_compatible flag for this stream in the topology, but this PR will power off the iDisp link when calling hda_dsp_set_D0_state() to set D0I3 state...

@ranj063 do you follow me?

2021-02-04 15:40 UTC, plbossart commented
> Imagine that if we want to run HDMI audio on D0i3 and specify d0i3_compatible flag for this stream in the topology, but this PR will power off the iDisp link when calling hda_dsp_set_D0_state() to set D0I3 state...
> 
> @ranj063 do you follow me?

if you specify that the stream is D0i3 compatible then it's got to be supported in hardware. If you put crazy values in the topology you will get random behavior. The only ask at this point is that the values in the topology don't result in a system crash, but there is no requirement that the system be functional when you ask it to do silly things.

2021-02-04 16:28 UTC, ranj063 commented
> > > Hi @ranj063 @kv2019i @plbossart only one concern here, is our Audio IP designed to run iDisp link with D0i3 set? If so, maybe not wise to power down dsp link blindly here, otherwise, we might need revisit this part and back and forth change could happen.
> > 
> > 
> > D0i3 is opt-in, we have to specify which streams/outputs are D0i3 compatible so we are in complete control here.
> 
> Imagine that if we want to run HDMI audio on D0i3 and specify d0i3_compatible flag for this stream in the topology, but this PR will power off the iDisp link when calling hda_dsp_set_D0_state() to set D0I3 state...
> 
> @ranj063 do you follow me?

@keyonjie no it wont. We also make sure to check that the hdac bus is powered off before turning off the link.

2021-02-04 16:29 UTC, ranj063 commented
> > > > Hi @ranj063 @kv2019i @plbossart only one concern here, is our Audio IP designed to run iDisp link with D0i3 set? If so, maybe not wise to power down dsp link blindly here, otherwise, we might need revisit this part and back and forth change could happen.
> > > 
> > > 
> > > D0i3 is opt-in, we have to specify which streams/outputs are D0i3 compatible so we are in complete control here.
> > 
> > 
> > Imagine that if we want to run HDMI audio on D0i3 and specify d0i3_compatible flag for this stream in the topology, but this PR will power off the iDisp link when calling hda_dsp_set_D0_state() to set D0I3 state...
> > @ranj063 do you follow me?
> 
> @keyonjie no it wont. We also make sure to check that the hdac bus is powered off before turning off the link.

I mean all all codecs on the bus are powered off.

2021-02-04 16:59 UTC, kv2019i commented
@keyonjie I think this is ok. The patch does check whether iDisp codec is powered and will not disable the link if it is.

If we have a D0i3-compatible iDisp stream, the codec would have to be powered, so no action would be taken by this new code. DSP could enter D0i3, but HDA controller, link and the codec would all remain powered.

2021-02-05 01:55 UTC, keyonjie commented
> @keyonjie I think this is ok. The patch does check whether iDisp codec is powered and will not disable the link if it is.
> 
> If we have a D0i3-compatible iDisp stream, the codec would have to be powered, so no action would be taken by this new code. DSP could enter D0i3, but HDA controller, link and the codec would all remain powered.

Oh, I didn't see this, then I am good, thanks.

2021-02-05 01:55 UTC, keyonjie approved these changes

2021-02-05 06:47 UTC, merged

2021-02-05 08:09 UTC, kv2019i commented
Doh, @ranj063 and @keyonjie I just realized we could greatly simplify this patch when https://github.com/thesofproject/linux/pull/2732 . If iDisp codec is suspended, PR2732 will disable both link and DMA. So only thing left to do for D0i3.

Let me work on this today.

2021-02-05 08:15 UTC, ranj063 commented
> Doh, @ranj063 and @keyonjie I just realized we could greatly simplify this patch when #2732 . If iDisp codec is suspended, PR2732 will disable both link and DMA. So only thing left to do for D0i3.
> 
> Let me work on this today.

@kv2019i I thought about this but I left it nevertheless because it simplifies the flow for S0 and S0ix