SoundWire: ADR quirks take 2
thesofproject/linux pull request #2754
Opened 2021-02-10 23:30 UTC by plbossart

second version to address upstream comments.
Replace #2743

2021-02-18 08:16 UTC, RanderWang approved these changes, later dismissed

2021-02-22 08:23 UTC, bardliao requested changes
`bool find_slave()` should return false instead of 0.

2021-02-22 08:23 UTC, bardliao commented on drivers/soundwire/slave.c
> +		return 0;
`bool find_slave()` should return false.

2021-02-22 15:54 UTC, plbossart commented on drivers/soundwire/slave.c
> +		return 0;
ah yes, this was changed to long long but I changed it back to a bool without changing the return value. Will fix.

2021-02-22 16:51 UTC, plbossart commented on drivers/soundwire/slave.c
> +		return 0;
fixed now

2021-02-23 05:51 UTC, bardliao approved these changes

2021-02-23 07:12 UTC, RanderWang approved these changes

2021-02-23 07:56 UTC, lyakh approved these changes

2021-02-23 15:23 UTC, merged