ASoC: SOF: Intel: hda: add hda_dsp_core_is_disabled function
thesofproject/linux pull request #2771
Opened 2021-03-01 06:01 UTC by xiulipan

If hda_dsp_core_is_enabled return 0, it does not mean that the core
is disabled. There status could be core is powering up/down.

2021-03-01 14:59 UTC, plbossart requested changes
I could use more comments or explanations on what problem this is solving and how the change in logic helps, I don't follow what this PR brings.

2021-03-02 03:08 UTC, xiulipan commented
@plbossart Would the below commit update help? It is indeed a very complex issue as we are tracking few bits to get the DSP CORE power status.

DSP core status is controlled by ADSPCS register.
The DSP is enabled when ADSPCS_SPA and ADSPCS_CPA bit is 1 and ADSPCS_CRST and ADSPCS_CSTALL is 0.
If we just set ADSPCS_SPA to 0 to power off the DSP core, the process can take some time and the hda_dsp_core_is_enabled 
will return 0 now. But this 0 do not means the CORE is disabled, it can also means the CORE is powering up/down process.

Create a new hda_dsp_core_is_disabled function to check ADSPCS_SPA and ADSPCS_CPA bit is 0 and ADSPCS_CRST and ADSPCS_CSTALL is 1 for CORE power off status

2021-03-02 06:42 UTC, ranj063 commented on sound/soc/sof/intel/hda-dsp.c
> +		      !(val & HDA_DSP_ADSPCS_SPA_MASK(core_mask)) &&
why do we need to check SPA? Isnt CPA enough?

2021-03-02 06:46 UTC, ranj063 commented on sound/soc/sof/intel/hda-dsp.c
> +		      !(val & HDA_DSP_ADSPCS_SPA_MASK(core_mask)) &&
Im still confused about what issue this fixes? Where do you see this problem where you expect the core to be OFF but it is in the middle of a transition?

2021-03-02 15:18 UTC, plbossart commented
> @plbossart Would the below commit update help? It is indeed a very complex issue as we are tracking few bits to get the DSP CORE power status.
> 
> DSP core status is controlled by ADSPCS register.
> The DSP is enabled when ADSPCS_SPA and ADSPCS_CPA bit is 1 and ADSPCS_CRST and ADSPCS_CSTALL is 0.
> If we just set ADSPCS_SPA to 0 to power off the DSP core, the process can take some time and the hda_dsp_core_is_enabled
> will return 0 now. But this 0 do not means the CORE is disabled, it can also means the CORE is powering up/down process.

I don't think it's possible. We set the SPA bits but we wait for the CPA bits to be match what was set in SPA. That tells us the core IS powered down. If it fails to power down, we will have a timeout.
 
> Create a new hda_dsp_core_is_disabled function to check ADSPCS_SPA and ADSPCS_CPA bit is 0 and ADSPCS_CRST and ADSPCS_CSTALL is 1 for CORE power off status

Like I said above, I don't think you can have CPA !=0 by the time you check the other bits. So the logic change should not matter.

I agree with @ranj063 that there is no clear rationale for merging this for now. We may be wrong but you haven't convinced us with evidence or data.

2021-03-08 02:56 UTC, closed without merging