ASoC: SOF: core: harden shutdown helper
thesofproject/linux pull request #2791
Opened 2021-03-15 15:45 UTC by plbossart

When the probe is handled in a workqueue, we must use
cancel_work_sync() in the shutdown helper to avoid possible race
conditions.

Likewise, when a failure occurs in a workqueue, we should not try to
access hardware registers and create more problems

Fixes: daff7f1478e12 ("ASoC: SOF: add snd_sof_device_shutdown() helper for shutdown")
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

2021-03-15 20:25 UTC, ranj063 submitted a review, later dismissed

2021-03-15 23:32 UTC, plbossart commented
This PR needs more work, when an error occurs during the pm_runtime_resume() done in pci_shutdown(), then the firmware boot may be IN_PROGRESS. The use of state > FW_BOOT_NOT_STARTED is not fully correct, this doesn't cover an error on resume. @ranj063 I'll need your help on this one.

[upextreme-reboot-loop.txt](https://github.com/thesofproject/linux/files/6145052/upextreme-reboot-loop.txt)

2021-03-16 00:28 UTC, plbossart commented
It looks like we have a race condition somewhere. The log below shows a correlation between the failures and actually resuming in pci_device_shutdown. When something triggers an earlier resume, there is no issue.

[upextreme-reboot-loop2.txt](https://github.com/thesofproject/linux/files/6145227/upextreme-reboot-loop2.txt)

working pattern

````
[   41.200229] systemd-shutdown[1]: Rebooting.
[   41.201592] sof-audio-pci-intel-cnl 0000:00:1f.3: pci_device_shutdown: pm_runtime_resume: start
[   41.202823] sof-audio-pci-intel-cnl 0000:00:1f.3: pci_device_shutdown: pm_runtime_resume: done
[   41.203997] sof-audio-pci-intel-cnl 0000:00:1f.3: pci_device_shutdown: shutdown start
[   41.205184] sof-audio-pci-intel-cnl 0000:00:1f.3: snd_sof_device_shutdown: fw state 5
[   41.206374] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
[   41.207601] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[   41.208857] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[   41.210128] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[   41.211326] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[   41.212497] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[   41.213761] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[   41.214967] sof-audio-pci-intel-cnl 0000:00:1f.3: Turning i915 HDAC power 0
[   41.216231] sof-audio-pci-intel-cnl 0000:00:1f.3: Current DSP power state: D3
[   41.217465] sof-audio-pci-intel-cnl 0000:00:1f.3: pci_device_shutdown: shutdown done
[   41.222661] igb 0000:01:00.0: pci_device_shutdown: pm_runtime_resume: start
[   41.223860] igb 0000:01:00.0: pci_device_shutdown: pm_runtime_resume: done
[   41.225115] igb 0000:01:00.0: pci_device_shutdown: shutdown start
````

non-working pattern

````
[   23.239011] systemd-shutdown[1]: Rebooting.
[   23.240568] sof-audio-pci-intel-cnl 0000:00:1f.3: pci_device_shutdown: pm_runtime_resume: start
[   23.254216] sof-audio-pci-intel-cnl 0000:00:1f.3: Turning i915 HDAC power 1
[   23.260089] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
[   23.264536] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000040 at  00000048
[   23.265968] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIW: 00000000 at  00000048
[   23.270287] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[   23.271633] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIW: 00000040 at  00000048
[   23.274612] sof-audio-pci-intel-cnl 0000:00:1f.3: Turning i915 HDAC power 0
[   23.275989] sof-audio-pci-intel-cnl 0000:00:1f.3: Current DSP power state: D0I0
[   23.277380] sof-audio-pci-intel-cnl 0000:00:1f.3: loading firmware
[   23.278747] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000002 at  00000048
[   23.280129] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIW: 00000000 at  00000048
[   23.281484] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
[   23.282820] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIW: 00000004 at  00000044
[   23.284161] sof-audio-pci-intel-cnl 0000:00:1f.3: booting DSP firmware
[   23.285571] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[   23.286911] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[   23.288244] sof-audio-pci-intel-cnl 0000:00:1f.3: period_bytes:0x0
[   23.289620] sof-audio-pci-intel-cnl 0000:00:1f.3: periods:1
[   23.290957] sof-audio-pci-intel-cnl 0000:00:1f.3: Attempting iteration 0 of Core En/ROM load...
[   23.292236] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask f
[   23.293554] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0f successful
[   23.294898] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0xf0f0f00 successful
[   23.296197] sof-audio-pci-intel-cnl 0000:00:1f.3: unstall/run core: core_mask = f
[   23.297532] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask f
[   23.298932] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0xf0f0000 successful
[   23.300238] sof-audio-pci-intel-cnl 0000:00:1f.3: unstall/run core: core_mask = 1
[   23.301572] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[   23.803068] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0x0 timedout
[   23.804428] sof-audio-pci-intel-cnl 0000:00:1f.3: unknown ROM status value 05000001
[   23.805823] sof-audio-pci-intel-cnl 0000:00:1f.3: status = 0x00000000 panic = 0x00000000
[   23.807164] sof-audio-pci-intel-cnl 0000:00:1f.3: extended rom status:  0x5000001 0x0 0x0 0x0 0x0 0x0 0x1811102 0x0
````

2021-03-16 04:55 UTC, libinyang commented on sound/soc/sof/core.c
> +		cancel_work_sync(&sdev->probe_work);
@plbossart Maybe it is better to move this check into sof_suspend() as sof_suspend() still need this check?

2021-03-16 06:04 UTC, libinyang commented
> It looks like we have a race condition somewhere. The log below shows a correlation between the failures and actually resuming in pci_device_shutdown. When something triggers an earlier resume, there is no issue.
> 
> [upextreme-reboot-loop2.txt](https://github.com/thesofproject/linux/files/6145227/upextreme-reboot-loop2.txt)
> 
> working pattern
> 
> ```
> [   41.200229] systemd-shutdown[1]: Rebooting.
> [   41.201592] sof-audio-pci-intel-cnl 0000:00:1f.3: pci_device_shutdown: pm_runtime_resume: start
> [   41.202823] sof-audio-pci-intel-cnl 0000:00:1f.3: pci_device_shutdown: pm_runtime_resume: done
> [   41.203997] sof-audio-pci-intel-cnl 0000:00:1f.3: pci_device_shutdown: shutdown start
> [   41.205184] sof-audio-pci-intel-cnl 0000:00:1f.3: snd_sof_device_shutdown: fw state 5
> [   41.206374] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
> [   41.207601] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
> [   41.208857] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
> [   41.210128] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
> [   41.211326] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
> [   41.212497] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
> [   41.213761] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
> [   41.214967] sof-audio-pci-intel-cnl 0000:00:1f.3: Turning i915 HDAC power 0
> [   41.216231] sof-audio-pci-intel-cnl 0000:00:1f.3: Current DSP power state: D3
> [   41.217465] sof-audio-pci-intel-cnl 0000:00:1f.3: pci_device_shutdown: shutdown done
> [   41.222661] igb 0000:01:00.0: pci_device_shutdown: pm_runtime_resume: start
> [   41.223860] igb 0000:01:00.0: pci_device_shutdown: pm_runtime_resume: done
> [   41.225115] igb 0000:01:00.0: pci_device_shutdown: shutdown start
> ```
> 
> non-working pattern
> 
> ```
> [   23.239011] systemd-shutdown[1]: Rebooting.
> [   23.240568] sof-audio-pci-intel-cnl 0000:00:1f.3: pci_device_shutdown: pm_runtime_resume: start
> [   23.254216] sof-audio-pci-intel-cnl 0000:00:1f.3: Turning i915 HDAC power 1
> [   23.260089] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
> [   23.264536] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000040 at  00000048
> [   23.265968] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIW: 00000000 at  00000048
> [   23.270287] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
> [   23.271633] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIW: 00000040 at  00000048
> [   23.274612] sof-audio-pci-intel-cnl 0000:00:1f.3: Turning i915 HDAC power 0
> [   23.275989] sof-audio-pci-intel-cnl 0000:00:1f.3: Current DSP power state: D0I0
> [   23.277380] sof-audio-pci-intel-cnl 0000:00:1f.3: loading firmware
> [   23.278747] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000002 at  00000048
> [   23.280129] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIW: 00000000 at  00000048
> [   23.281484] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
> [   23.282820] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIW: 00000004 at  00000044
> [   23.284161] sof-audio-pci-intel-cnl 0000:00:1f.3: booting DSP firmware
> [   23.285571] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
> [   23.286911] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
> [   23.288244] sof-audio-pci-intel-cnl 0000:00:1f.3: period_bytes:0x0
> [   23.289620] sof-audio-pci-intel-cnl 0000:00:1f.3: periods:1
> [   23.290957] sof-audio-pci-intel-cnl 0000:00:1f.3: Attempting iteration 0 of Core En/ROM load...
> [   23.292236] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask f
> [   23.293554] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0f successful
> [   23.294898] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0xf0f0f00 successful
> [   23.296197] sof-audio-pci-intel-cnl 0000:00:1f.3: unstall/run core: core_mask = f
> [   23.297532] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask f
> [   23.298932] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0xf0f0000 successful
> [   23.300238] sof-audio-pci-intel-cnl 0000:00:1f.3: unstall/run core: core_mask = 1
> [   23.301572] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
> [   23.803068] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg=0x0 timedout
> [   23.804428] sof-audio-pci-intel-cnl 0000:00:1f.3: unknown ROM status value 05000001
> [   23.805823] sof-audio-pci-intel-cnl 0000:00:1f.3: status = 0x00000000 panic = 0x00000000
> [   23.807164] sof-audio-pci-intel-cnl 0000:00:1f.3: extended rom status:  0x5000001 0x0 0x0 0x0 0x0 0x0 0x1811102 0x0
> ```

@plbossart How did you save such message to the disk? I tried to save such message before but failed.

2021-03-16 14:39 UTC, plbossart commented
> @plbossart How did you save such message to the disk? I tried to save such message before but failed.

I used netconsole on UpExtreme, it's got two Ethernet ports. see instructions here: 

[netconsole.txt](https://github.com/thesofproject/linux/files/6149792/netconsole.txt)

it's almost like a UART but over Ethernet (UDP packets).

The difficulty is finding a device with an Ethernet port, I don't think this works too well with USB dongles.

2021-03-16 17:13 UTC, kv2019i requested changes
Hmm, somewhat with uneasy. The probe_complete error paths have been problematic enough in the past, so not sure how we keep the error unroll paths in shutdown working. It would seem a brute-force shutdown that makes no assumtpions that driver+fw did sane things before sutdown, would be more sure and this is a code ptah we test every time we reboot a machine.

2021-03-16 17:13 UTC, kv2019i commented on sound/soc/sof/core.c
> +
Not sure this is useful. User-space is shutdown, so this log won't be seen in any normal log (i.e. no syslog/systemd anymore). You'll need a serial/netconsole to catch these, and then you probably can add additional traces as well.

2021-03-16 17:13 UTC, kv2019i commented on sound/soc/sof/core.c
> +		cancel_work_sync(&sdev->probe_work);
@libinyang I think this is here to protect the conditional check on fw_state on L406. OTOH, the suspend case warrants a check as well, but the case is a bit different.

2021-03-16 17:13 UTC, kv2019i commented on sound/soc/sof/pm.c
> +	return ret;
This is very hard code to test for regressions, so I wonder if this is practical to add this. I mean if previously functioning device fails to boot after resume, something pretty bad has gone through.

I think it would be safer to have a more robust shutdown logic that would just shutdown the.

2021-03-16 18:21 UTC, plbossart commented
@ranj063 @kv2019i @libinyang see new log below. What's interesting is that *something* (PulseAudio?) opens a PCM device after the reboot command is issued, and the PCI device does a pm_runtime suspend while the reboot sequence is happening.

[upextreme-reboot-loop5.txt](https://github.com/thesofproject/linux/files/6151389/upextreme-reboot-loop5.txt)

2021-03-16 18:27 UTC, plbossart commented
branch updated in case someone wants to give it a try with the same setup

2021-03-16 18:39 UTC, plbossart commented
@ranj063 @kv2019i @libinyang now I have a sequence that is 100% reproducible.

When removing PulseAudio, there is no longer a pm_runtime_resume and pcm_open(), so the device has to be resumed in the shutdown sequence and that fails ALL THE TIME.

So it's really going back to D0 in the shutdown sequence that's problematic. If the device is in D0 the shutdown works fine.

[upextreme-reboot-loop6.txt](https://github.com/thesofproject/linux/files/6151476/upextreme-reboot-loop6.txt)

I now suspect something in the PCI core that's doing things that get in the way of resuming?

2021-03-17 12:43 UTC, kv2019i commented
@plbossart wrote:
> So it's really going back to D0 in the shutdown sequence that's problematic. If the device is in D0 the shutdown works fine.
> 
> [upextreme-reboot-loop6.txt](https://github.com/thesofproject/linux/files/6151476/upextreme-reboot-loop6.txt)
> 
> I now suspect something in the PCI core that's doing things that get in the way of resuming?

Hmm, that could happen. I wonder if we could detect that we are shutting down somehow in the PM resume flow (and not really boot the DSP anymore). OTOH, this probably won't work as shutdown/reboot is not directly related to how kernel does suspend/resume.

This is still really strange why the boot fails. Some actions towards the DSP work. If some PCI level resources would have been taken down, I'd expect all I/O to fail. Maybe the fw-auth is not working anymore -- seems we don't complete the ROM execution successfully.

2021-03-18 02:33 UTC, libinyang commented
> @ranj063 @kv2019i @libinyang now I have a sequence that is 100% reproducible.
> 
> When removing PulseAudio, there is no longer a pm_runtime_resume and pcm_open(), so the device has to be resumed in the shutdown sequence and that fails ALL THE TIME.
> 
> So it's really going back to D0 in the shutdown sequence that's problematic. If the device is in D0 the shutdown works fine.
> 
> [upextreme-reboot-loop6.txt](https://github.com/thesofproject/linux/files/6151476/upextreme-reboot-loop6.txt)
> 
> I now suspect something in the PCI core that's doing things that get in the way of resuming?

@plbossart I tried on my tgl board and I can't reproduce this issue with disabling or enabling the pulseaudio. And all our CI DUTs do the test with PA disabled. They will reboot after test, but we didn't find such issue on all DUTs. If this issue hangs at pm-runtime resume in shutdown, can we reproduce this issue in pure pm-runtime suspend/resume?

2021-03-18 05:49 UTC, libinyang commented
> This is still really strange why the boot fails. Some actions towards the DSP work. If some PCI level resources would have been taken down, I'd expect all I/O to fail. Maybe the fw-auth is not working anymore -- seems we don't complete the ROM execution successfully.

@kv2019i And it is strange that it shows "DSP core(s) enabled? 1 : core_mask f". I remember we only enable 1 core, do we?

2021-03-18 23:06 UTC, plbossart commented
> > @ranj063 @kv2019i @libinyang now I have a sequence that is 100% reproducible.
> > When removing PulseAudio, there is no longer a pm_runtime_resume and pcm_open(), so the device has to be resumed in the shutdown sequence and that fails ALL THE TIME.
> > So it's really going back to D0 in the shutdown sequence that's problematic. If the device is in D0 the shutdown works fine.
> > [upextreme-reboot-loop6.txt](https://github.com/thesofproject/linux/files/6151476/upextreme-reboot-loop6.txt)
> > I now suspect something in the PCI core that's doing things that get in the way of resuming?
> 
> @plbossart I tried on my tgl board and I can't reproduce this issue with disabling or enabling the pulseaudio. And all our CI DUTs do the test with PA disabled. They will reboot after test, but we didn't find such issue on all DUTs. If this issue hangs at pm-runtime resume in shutdown, can we reproduce this issue in pure pm-runtime suspend/resume?

You can only see the issue if you have netconsole or a UART link. If you don't then you would never know there was a problem.

2021-03-19 08:20 UTC, libinyang commented
> 
> You can only see the issue if you have netconsole or a UART link. If you don't then you would never know there was a problem.

@plbossart I captured the dmesg with a camera. It shows OK. Please see the attachment.
![112317145](https://user-images.githubusercontent.com/10509113/111751017-ed408080-88ce-11eb-8a06-a0db7a23ef4e.jpg)

2021-03-19 16:46 UTC, plbossart commented
> > You can only see the issue if you have netconsole or a UART link. If you don't then you would never know there was a problem.
> 
> @plbossart I captured the dmesg with a camera. It shows OK on my TGL platform. Please see the attachment. (I have disabled PA)
> ![112317145](https://user-images.githubusercontent.com/10509113/111751017-ed408080-88ce-11eb-8a06-a0db7a23ef4e.jpg)

Ack, that's useful. thanks @libinyang. I think we have possible BIOS issues here.

2021-03-19 18:18 UTC, plbossart commented
@libinyang @kv2019i @ranj063 I went back to a minimal fix, we'll have to deal with the firmware authentication during pm_runtime_resume as a separate, possibly device-specific, issue.

2021-03-19 18:57 UTC, ranj063 approved these changes

2021-03-19 20:04 UTC, kv2019i approved these changes

2021-03-22 01:14 UTC, libinyang approved these changes
LGTM

2021-03-22 10:21 UTC, merged