ASoC: SOF: topology: return error if sof_connect_dai_widget() fails
thesofproject/linux pull request #2834
Opened 2021-04-09 02:20 UTC by ranj063

Return the error if sof_connect_dai_widget() fails to
abort topology loading and prevent card registration.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

2021-04-09 06:06 UTC, lyakh requested changes

2021-04-09 06:06 UTC, lyakh commented on sound/soc/sof/topology.c
> +			}
I'd rather unite the two failure cases:
```
	ret = sof_widget_load_dai(scomp, index, swidget, tw, dai);
	if (!ret)
		ret = sof_connect_dai_widget(scomp, w, tw, dai);
	if (ret < 0) {
		kfree(dai);
		break;
	}
	list_add(&dai->list, &sdev->dai_list);
	swidget->private = dai;
```

2021-04-13 17:19 UTC, ranj063 commented on sound/soc/sof/topology.c
> +			}
thanks, done!

2021-04-13 20:04 UTC, plbossart approved these changes

2021-04-14 08:38 UTC, lyakh approved these changes

2021-04-14 15:30 UTC, merged