ASoC: SOF: probes support related cleanups
thesofproject/linux pull request #3014
Opened 2021-06-28 10:49 UTC by ujfalusi

Hi,

as requested by @plbossart, I have split out the cleanup patches regarding to the probes support from #3007
The probes conversion to SOF client depends on this series.

2021-06-28 11:01 UTC, kv2019i requested changes
One minor note on a git commit message, otherwise looks great!

2021-06-28 11:01 UTC, kv2019i commented on sound/soc/sof/pcm.c
Maybe add a fixes line pointing to "ASoC: SOF: remove compressed streams". At least I'm left wondering how such code could have ended up in the kernel.... but the above commit explains.

2021-06-28 11:07 UTC, ujfalusi commented on sound/soc/sof/pcm.c
@kv2019i, thanks for pointing it out, I have not looked at the history, but this explains why it was there.
Updated the PR with the Fixes tag (btw: baa58ecfe32950dc1ee98455de5bceafd8520463 is not "upstream")

2021-06-28 11:34 UTC, ujfalusi commented on sound/soc/sof/pcm.c
I stand corrected, the patch should apply upstream as well, we have the same remains there, but it is a bit problematic to find the commit to blame there.

2021-06-28 15:31 UTC, plbossart commented on sound/soc/sof/pcm.c
or remove the Fixes tag, it's not really that bad. This removes dead-code, that's more of an improvement.

2021-06-28 15:32 UTC, plbossart reviewed
looks ok @ujfalusi only the second commit message needs to be updated. I suggest removing the fixes tag.

2021-06-28 15:51 UTC, ujfalusi commented
@plbossart, thank you, I'll update the PR in few minutes to remove the Fixes tag.

2021-06-28 15:54 UTC, ujfalusi commented
Changes since v2:
- removed fixes tag from patch two

Changes since v1:
- added fixes tag to commit two

2021-06-28 16:01 UTC, plbossart submitted a review, later dismissed
LGTM @ujfalusi thanks for the cleanup!

2021-06-29 07:18 UTC, dbaluta submitted a review, later dismissed

2021-06-29 07:19 UTC, dbaluta commented
Looks good to me! Thanks @ujfalusi.

2021-06-29 11:06 UTC, ujfalusi commented
Hi,

pushed one more patch to use correct postfix for the functions used in snd_soc_cdai_ops for startup and shutdown.

Sorry for the late update but I wanted to include it to this PR and not take it via the auxbus support.

2021-06-29 15:52 UTC, plbossart approved these changes

2021-06-29 16:26 UTC, kv2019i approved these changes

2021-06-29 16:42 UTC, ranj063 approved these changes

2021-06-29 21:22 UTC, merged