Fixup! ASoC: SOF: Intel: Update ADL descriptor to use ACPI power states
thesofproject/linux pull request #3033
Opened 2021-07-08 08:29 UTC by sathyap-chrome

ADL descriptor was missing acpi power setting
Hence the DSP was entering D3 even with wov stream.

Signed-off-by: Sathya Prakash M R <sathya.prakash.m.r@intel.com>

2021-07-08 08:31 UTC, sathyap-chrome commented
Thanks to @ranj063 for pointers in https://github.com/thesofproject/linux/issues/3026

This fixes the issue. verified Intel clap wakes from soix

2021-07-08 08:31 UTC, sofci commented
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

2021-07-08 08:35 UTC, sathyap-chrome commented
cc @kv2019i @jairaj-arava @Vamshigopal

2021-07-08 13:27 UTC, ranj063 approved these changes, later dismissed

2021-07-08 13:28 UTC, ranj063 commented
> Can one of the admins verify this patch?
> 
> > reply **test this please** to run this test once

test this please

2021-07-08 14:41 UTC, plbossart approved these changes

2021-07-08 14:44 UTC, plbossart requested changes
sorry, this is not a fixup!, the code is already upstream.

Please remove the fixup! in the commit subject and add a tag
````
Fixes: 4ad03f894b3c ('ASoC: SOF: Intel: Update ADL P to use its own descriptor')
````

2021-07-08 14:57 UTC, sathyap-chrome commented
@plbossart corrected. thanks.

2021-07-08 14:59 UTC, ranj063 approved these changes

2021-07-08 15:02 UTC, plbossart approved these changes

2021-07-09 05:27 UTC, ranj063 commented
Test this please

2021-07-09 13:27 UTC, plbossart commented
Fail on ADL_NOCODEC is due to bad mixer values, being fixed. let's merge

2021-07-09 13:29 UTC, merged