ASoC: SOF: Intel: ICL: move ICL-specific ops to icl.c
thesofproject/linux pull request #3082
Opened 2021-08-04 17:47 UTC by ranj063

Move the ICL specific ops to icl.c. Also introduce a
macro ICL_DSP_HPRO_CORE_ID to define the core that
should be powered up when HPRO is enabled.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

2021-08-04 17:55 UTC, plbossart approved these changes

2021-08-05 01:27 UTC, bardliao approved these changes

2021-08-05 14:39 UTC, kv2019i requested changes
Should the comments be updated as well?

2021-08-05 14:39 UTC, kv2019i commented on sound/soc/sof/intel/icl.c
> + * Core 3 will be powered up and in stall when HPRO is enabled
s/3/ICL_DSP_HPRO_CORE_ID/?

2021-08-05 14:39 UTC, kv2019i commented on sound/soc/sof/intel/icl.c
> +	 * power up core 3 and keep it in stall if HPRO is enabled.
ICL_DSP_HPRO_CORE_ID?

2021-08-05 16:47 UTC, ranj063 commented
> Should the comments be updated as well?

@kv2019i isnt it better to say 3 in the comments to make it easier for the reader?

2021-08-06 13:37 UTC, kv2019i commented
@ranj063 wrote:
>> Should the comments be updated as well?
> 
> @kv2019i isnt it better to say 3 in the comments to make it easier for the reader?

Hmm, as ICL_DSP_HPRO_CORE_ID is defined at the start, it requires reader to look it up. But, but, if this was intentional, ok for me, let's go with this.

2021-08-06 13:37 UTC, kv2019i approved these changes

2021-08-10 20:49 UTC, merged