ASoC: Intel: sof_sdw: tag SoundWire BEs as non-atomic
thesofproject/linux pull request #3089
Opened 2021-08-10 00:41 UTC by plbossart

The SoundWire BEs make use of 'stream' functions for .prepare and
.trigger. These functions will in turn force a Bank Switch, which
implies a wait operation.

Mark SoundWire BEs as nonatomic for consistency, but keep all other
types of BEs as is.

Suggested-by: Takashi Iwai <tiwai@suse.de>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

2021-08-10 00:47 UTC, ranj063 submitted a review, later dismissed

2021-08-10 01:33 UTC, bardliao approved these changes, later dismissed

2021-08-10 01:35 UTC, RanderWang commented on sound/soc/intel/boards/sof_sdw.c
> +			  const struct snd_soc_ops *ops, bool nonatomic)
one more args for init_dai_link. Can we make it "static inline void", then args count is not a problem.

2021-08-10 12:00 UTC, kv2019i requested changes
Hmm, init_dai_link() is starting to be ready hard to follow.

2021-08-10 12:00 UTC, kv2019i commented on sound/soc/intel/boards/sof_sdw.c
> +			      NULL, &sdw_ops, true);
Adding booleans to init_dai_link() makes it even harder to follow. How about just setting nonatomic to true here in a separate call outside init_dai_link (with a comment that notes SDW uses nonatomic stream ops and thus the nonatomic flag needs to be set)?  No need to modify other places where init_dai_link is called.

2021-08-10 16:09 UTC, plbossart commented on sound/soc/intel/boards/sof_sdw.c
> +			      NULL, &sdw_ops, true);
good suggestion @kv2019i, I just made that change.

2021-08-11 01:24 UTC, RanderWang approved these changes

2021-08-11 16:43 UTC, ranj063 approved these changes

2021-08-12 06:42 UTC, bardliao approved these changes

2021-08-12 13:38 UTC, merged