Trace fixes
thesofproject/linux pull request #3166
Opened 2021-09-17 21:29 UTC by ranj063

2021-09-20 15:30 UTC, kv2019i requested changes
Partial review, commenting on the first patch.

2021-09-20 15:30 UTC, kv2019i commented on sound/soc/sof/trace.c
>  }
Hmm, how can you be sure the user-space thread is not in sof_wait_trace_avail() ? The release trace can be called when sof-logger is still running and waiting for traces.

2021-09-20 15:30 UTC, kv2019i commented on sound/soc/sof/intel/hda-dai.c
>  	struct snd_soc_pcm_runtime *rtd = asoc_substream_to_rtd(substream);
typo in commit: dma_sata in subject

2021-09-20 15:44 UTC, plbossart commented
@ranj063 I think there should be two separate PRs here
a) your last commit that should apply to all platforms
b) S0ix-related changes - on which I agree with @kv2019i that the fix is controversial.

I don't think we should bundle the two parts, it's better for validation if we split, no?

2021-09-21 03:05 UTC, ranj063 commented
to be replaced with a better fix

2021-09-21 03:05 UTC, closed without merging