Remove RESUME trigger handling
thesofproject/linux pull request #3323
Opened 2021-12-09 05:23 UTC by ranj063

2021-12-09 12:42 UTC, RanderWang reviewed
could you explain "full resume" ? Thanks!

2021-12-09 15:12 UTC, plbossart commented
> could you explain "full resume" ? Thanks!

Agree with @RanderWang. We should state that the driver does not support the INFO_RESUME capability and resuming needs to be handled by the ALSA core with the .prepare and .trigger_start stages.

2021-12-09 17:31 UTC, ranj063 commented
> > could you explain "full resume" ? Thanks!
> 
> Agree with @RanderWang. We should state that the driver does not support the INFO_RESUME capability and resuming needs to be handled by the ALSA core with the .prepare and .trigger_start stages.

done. thanks!

2021-12-09 17:33 UTC, plbossart requested changes

2021-12-09 17:33 UTC, plbossart commented on sound/soc/sof/pcm.c
> -	case SNDRV_PCM_TRIGGER_RESUME:
typo in commit message: iremove.

2021-12-09 18:04 UTC, plbossart approved these changes, later dismissed

2021-12-10 10:24 UTC, kv2019i requested changes
Please add a reference to "ASoC: SOF: pcm: do not add SNDRV_PCM_INFO_RESUME to runtime hw info". This looks really odd otherwise. Why all this code if the feature is not supported.

2021-12-10 11:02 UTC, RanderWang submitted a review, later dismissed

2021-12-10 12:46 UTC, bardliao commented
So driver will return error if it got trigger resume? What is the benefit of this PR?

2021-12-10 14:51 UTC, plbossart commented
> So driver will return error if it got trigger resume? What is the benefit of this PR?

we can't have TRIGGER_RESUME because INFO_RESUME is not supported @bardliao. So the ALSA core will instead use .prepare and TRIGGER_START, as for xrun handling. The only difference between resume and xrun is that in the latter case we don't need to reinitialize any hardware, whereas in the resume case the device might have been power-gated or reset.

2021-12-10 14:52 UTC, plbossart commented
> Please add a reference to "ASoC: SOF: pcm: do not add SNDRV_PCM_INFO_RESUME to runtime hw info". This looks really odd otherwise. Why all this code if the feature is not supported.

yes, if we had two developers that missed the idea we probably need to expand on the explanations @ranj063. Thanks!

2021-12-10 16:25 UTC, ranj063 commented
> > Please add a reference to "ASoC: SOF: pcm: do not add SNDRV_PCM_INFO_RESUME to runtime hw info". This looks really odd otherwise. Why all this code if the feature is not supported.
> 
> yes, if we had two developers that missed the idea we probably need to expand on the explanations @ranj063. Thanks!

will do. But given that the change is because of a common flag in hw_info, do you still want 3 patches? I think we can squash them all into one, right?

2021-12-10 16:31 UTC, plbossart commented
> will do. But given that the change is because of a common flag in hw_info, do you still want 3 patches? I think we can squash them all into one, right?

Better to have separate patches, one change is for the core and the rest if for Intel stuff.

2021-12-13 15:57 UTC, plbossart approved these changes

2021-12-13 17:20 UTC, kv2019i approved these changes

2021-12-13 20:21 UTC, plbossart commented
let's give @bardliao and @RanderWang the opportunity to review again.

2021-12-14 02:39 UTC, RanderWang approved these changes
LGTM

2021-12-14 07:42 UTC, bardliao approved these changes
Thanks @ranj063

2021-12-14 14:05 UTC, merged