ASoC: soc-core: filter use of 'ignore_machine' field
thesofproject/linux pull request #3352
Opened 2022-01-03 15:24 UTC by yaochunhung

The 'ignore_machine' field is currently used to ignore all FE dailinks
statically added by the machine drivers, as well as override the
fixups for the BE dailinks. The motivation for this field was
primarily to reuse the same machine driver on Intel devices, both with
legacy and SOF-based platform drivers.

SOF is now used on Mediatek platforms, where the same card uses
SOF-based dailinks to deal with DSP-managed streams, as well as
'regular' dailinks. The 'ignore_machine' field set by the core SOF
platform driver is too strong, with dailinks not managed by SOF being
modified.

This patch adds a stricter filtering so that only dailinks managed by
a topology-based SOF driver are modified.

Reported-by: YC Hung <yc.hung@mediatek.com>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

2022-01-03 15:26 UTC, yaochunhung commented
Create this PR from https://github.com/thesofproject/linux/pull/3236 to verify sof-ci test

2022-01-04 10:56 UTC, kv2019i commented
Took a bit of time to understand what's this about. So basicly this is resubmitting the patch that was merged once, but then reverted in https://github.com/thesofproject/linux/pull/3294 . 

It seems failures are similar as before. A number of Intel SDW mach drivers fail to probe with this patch:
```
[   13.339685] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: loading topology:intel/sof-tplg/sof-cml-rt700.tplg
[   13.340698] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: Topology: ABI 3:20:0 Kernel ABI 3:18:0
[   13.340702] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: warn: topology ABI is more recent than kernel
[   13.340706] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: tplg: ready widget id 0 pipe 1 type 4 name : MIXER1.0 stream none
[   13.340712] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: tplg: load control type 1 name : 1 Master Playback Volume
[   13.340716] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: tplg: load kcontrol index 1 chans 2
[   13.340718] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: tplg: ready widget id 1 pipe 1 type 6 name : PGA1.0 stream none
[   13.340721] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: tplg: ready widget id 2 pipe 1 type 27 name : ALH0x102.OUT stream SDW1-Playback
[   13.340724] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: can't connect DAI ALH0x102.OUT stream SDW1-Playback
[   13.340736] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: failed to add widget id 0 type 27 name : ALH0x102.OUT stream SDW1-Playback
[   13.340748] kernel: sof_sdw sof_sdw: ASoC: failed to load widget ALH0x102.OUT
```

2022-01-04 10:58 UTC, kv2019i requested changes
@bardliao as this seems to affect SDW machine only, can you spot anything obvious in the filter checks that affects SDW?

2022-01-04 11:07 UTC, yaochunhung commented on sound/soc/soc-core.c
> +				continue;
@plbossart  I modify this to check if it work but it seems not. Could you please help to check if the modification is fine or need original conditional checking as below. Thanks.
```c
if (!dai || dai->component != component) 
    continue;
```

2022-01-06 05:43 UTC, bardliao commented
> @bardliao as this seems to affect SDW machine only, can you spot anything obvious in the filter checks that affects SDW?

Sure, I will take a look.

2022-01-06 07:17 UTC, bardliao commented
The SDW dais are created and registered by intel soundwire driver. (drivers/soundwire/intel.c). So the dai->component is different from the SOF component.

2022-01-11 01:08 UTC, cujomalainey commented
> The SDW dais are created and registered by intel soundwire driver. (drivers/soundwire/intel.c). So the dai->component is different from the SOF component.

ah yes I see what you mean, hmm, do we want to maybe make a allow-list of component names for SOF to take over? All other alternatives go back to either marking the link or the component for this specific case which seems like it should be SOF/SDW code to determine this, not ASoC

2022-05-17 21:55 UTC, plbossart commented
this PR seems to be abandoned or without a clear direction @yaochunhung ?

2022-05-18 05:41 UTC, yaochunhung commented
@plbossart We still use the patch on internal branch but currently I don't have good solution to fix the issue of SOF/SDW based on this PR. Thanks.

2022-08-09 08:18 UTC, plbossart commented
@yaochunhung this PR has been marked as 'Unclear' for several weeks. Unless there's an update and/or a need for comments, we should close this PR. You can always resubmit a new one later, it's just not efficient to leave such PRs dangling without any progress.

2022-08-09 08:58 UTC, yaochunhung commented
@plbossart I will close this PR. Thanks.

2022-08-09 08:58 UTC, closed without merging