ASoC: Intel: sof_rt5682: Add support for case of without speaker amp
thesofproject/linux pull request #3371
Opened 2022-01-15 15:22 UTC by brentlu

Add a board config adl_rt5682 to support alc5682 headset codec without
speaker amplifier. Follow Intel BT offload design by connecting
alc5682 to SSP0.

Signed-off-by: Ajye Huang <ajye_huang@compal.corp-partner.google.com>
Signed-off-by: Brent Lu <brent.lu@intel.com>

2022-01-17 17:34 UTC, plbossart requested changes
nit-pick below, looks good otherwise.

2022-01-17 17:34 UTC, plbossart commented on sound/soc/intel/boards/sof_rt5682.c
> +					SOF_SSP_BT_OFFLOAD_PRESENT),
commit title: ASoC: Intel: sof_rt5682: Add support for platform without amplifier.

2022-01-18 00:51 UTC, brentlu commented
update the title of commit

2022-01-18 08:43 UTC, brentlu commented
SOF PR: https://github.com/thesofproject/sof/pull/5218

2022-01-18 15:26 UTC, ranj063 approved these changes

2022-01-18 15:45 UTC, plbossart approved these changes

2022-01-18 15:46 UTC, merged