ASoC: SOF: mediatek: Revise mt8195 boot flow
thesofproject/linux pull request #3450
Opened 2022-02-21 11:17 UTC by yaochunhung

Hi,
This patch will fix statVectorSel wrong setting and modify shutdown flow to pull dsp runstall high before reset dsp to avoid unexpected error.
Pleas help to review it. Thanks.

2022-03-08 08:36 UTC, yaochunhung commented
SOFCI TEST

2022-03-08 13:34 UTC, ujfalusi requested changes
@yaochunhung, I would separate the patch to a fix (STATVECTOR_SEL correction) and the rest.

2022-03-08 13:34 UTC, ujfalusi commented on sound/soc/sof/mediatek/mt8195/mt8195-loader.c
> +				STATVECTOR_SEL, STATVECTOR_SEL);
This change should be a separate one with a Fixes: tag?

2022-03-10 03:00 UTC, yaochunhung commented on sound/soc/sof/mediatek/mt8195/mt8195-loader.c
> +				STATVECTOR_SEL, STATVECTOR_SEL);
OK. I will separate the patches and aslo use Fixes : tag for STATVECTOR_SEL. thanks.

2022-03-11 01:57 UTC, yaochunhung commented
SOFCI TEST

2022-03-11 07:34 UTC, yaochunhung commented
Hi all,
Could someone help to point out what happens for this test failure? I wonder why this PR cause this failure. Thanks.

2022-03-11 09:53 UTC, bardliao commented
> Hi all, Could someone help to point out what happens for this test failure? I wonder why this PR cause this failure. Thanks.

The check-suspend-resume-with-playback-5.sh and check-suspend-resume-with-capture-5.sh failures of TGLU_RVP_SDW is a known issue https://github.com/thesofproject/linux/issues/3459

2022-03-11 15:09 UTC, plbossart commented on sound/soc/sof/mediatek/mt8195/mt8195-loader.c
> +				STATVECTOR_SEL, STATVECTOR_SEL);
you can use a fixup! prefix if the code you are trying to fix has not landed in Mark Brown branch, or you need to provide a Fixes tag.
Which is it?

2022-03-14 01:32 UTC, yaochunhung commented on sound/soc/sof/mediatek/mt8195/mt8195-loader.c
> +				STATVECTOR_SEL, STATVECTOR_SEL);
Sorry for my misunderstanding, it should be Fixes: tag and I will modify it. Thanks.

2022-04-13 03:54 UTC, yaochunhung commented
Can someone help to review this PR? Thanks a lot.

2022-04-13 04:20 UTC, afq984 approved these changes

2022-04-13 16:14 UTC, plbossart approved these changes

2022-04-13 16:24 UTC, ranj063 approved these changes

2022-04-13 17:15 UTC, plbossart commented
@ujfalusi you good with this PR?

2022-06-08 02:28 UTC, yaochunhung commented
@ujfalusi  Could you please help to review this PR? Thanks.

2022-06-08 05:05 UTC, kuanhsuncheng approved these changes

2022-06-15 16:31 UTC, plbossart commented
@ujfalusi ping. You were the only reviewer requesting changes.

2022-06-30 02:09 UTC, kuanhsuncheng commented
Hi sirs, Are we all good with this PR?

2022-07-05 18:58 UTC, ujfalusi approved these changes

2022-07-05 19:44 UTC, merged