ASoC: SOF: mediatek: revise mt8195 clock sequence
thesofproject/linux pull request #3484
Opened 2022-03-06 03:17 UTC by yaochunhung

Hi,
This PR is used to revise mt8195 clock enable/disable flow. There are two clock modifications as below,
1.clock enable : enable and set audio_h selection as 26M.
2.clock disable : set parent of audio_local_bus as 26M.
  In DSP firmware, clock of audio_local_bus is swtiched to
  26M when suspend. To make sure that host kernel and dsp
  firmware are consistent, switch clock to 26M in kernel.
Please help to review it. Thanks.

2022-03-08 06:30 UTC, aiChaoSONG approved these changes, later dismissed

2022-03-08 08:34 UTC, yaochunhung commented
SOFCI TEST

2022-03-08 14:01 UTC, ujfalusi commented on sound/soc/sof/mediatek/mt8195/mt8195-clk.c
> +			return ret;
Is it OK to leave the clocks enabled if the reparent fail?

2022-03-08 14:01 UTC, ujfalusi commented on sound/soc/sof/mediatek/mt8195/mt8195-clk.c
> +			return ret;
Probably do the set parent after the adsp_disable_all_clocks() call?

2022-03-08 14:01 UTC, ujfalusi commented on sound/soc/sof/mediatek/mt8195/mt8195-clk.c
> +			return ret;
I suppose it is OK to leave the other clocks with their newly set parents?

2022-03-09 19:16 UTC, plbossart requested changes

2022-03-09 19:16 UTC, plbossart commented on sound/soc/sof/mediatek/mt8195/mt8195-clk.c
> +		ret = clk_set_parent(priv->clk[CLK_TOP_AUDIO_H],
typo in commit message: swtiched -> switched

2022-03-09 19:16 UTC, plbossart commented on sound/soc/sof/mediatek/mt8195/mt8195-clk.c
> +			return ret;
agree with @ujfalusi it's odd to reconfigure a running clock, and this isn't symmetrical with the enable case.

2022-03-10 01:09 UTC, yaochunhung commented on sound/soc/sof/mediatek/mt8195/mt8195-clk.c
> +		ret = clk_set_parent(priv->clk[CLK_TOP_AUDIO_H],
I will fix it. thanks.

2022-03-10 01:09 UTC, yaochunhung commented on sound/soc/sof/mediatek/mt8195/mt8195-clk.c
> +			return ret;
Basically my thought is to keep consistent with DSP side which switch audio_local_bus to 26M when enter suspend mode. But I think it should be fine to remove this due to clock will be disabled.
https://github.com/thesofproject/sof/blob/main/src/platform/mt8195/lib/clk.c#L166

2022-03-10 01:09 UTC, yaochunhung commented on sound/soc/sof/mediatek/mt8195/mt8195-clk.c
> +			return ret;
I want to keep these set parent check and return fail to avoid abnormal cases which may be caused by clock source is not ready.

2022-04-14 05:02 UTC, yaochunhung commented
Can someone help to review this PR? Thanks.

2022-05-03 20:50 UTC, plbossart approved these changes
approving but others need to review @ujfalusi @ranj063

2022-05-12 03:39 UTC, yaochunhung commented
@plbossart  Thanks. 
@ujfalusi @ranj063 Could you please help review this PR? Thanks.

2022-05-17 21:49 UTC, plbossart commented
@bardliao @ujfalusi @dbaluta @ranj063 can one of you please review so that we move on?

2022-05-19 10:03 UTC, bardliao approved these changes
LGTM

2022-05-19 10:54 UTC, ujfalusi approved these changes

2022-05-19 11:19 UTC, kuanhsuncheng approved these changes

2022-05-19 12:38 UTC, merged