ASoC: soc-acpi: Add entry for rt711-sdca-sdw in ADL match table
thesofproject/linux pull request #3487
Opened 2022-03-07 07:42 UTC by reddymur

RT711 sdca sdw is added with SDW0 link for ADL-PS platform.

Signed-off-by: Muralidhar Reddy <muralidhar.reddy@intel.com>

2022-03-07 07:43 UTC, sofci commented
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

2022-03-07 15:37 UTC, plbossart requested changes

2022-03-07 15:37 UTC, plbossart commented on sound/soc/intel/common/soc-acpi-intel-adl-match.c
> +		.sof_fw_filename = "sof-adl.ri",
no longer needed, this will not compile

2022-03-07 15:37 UTC, plbossart commented on sound/soc/intel/common/soc-acpi-intel-adl-match.c
> +	{
something's wrong with your indentation, not sure why lines 342/343 are off, and why the 346..349 are also off.

2022-03-09 14:51 UTC, plbossart approved these changes

2022-03-09 19:11 UTC, plbossart commented
@bardliao can you check this one and merge if you are ok?

2022-03-10 08:07 UTC, bardliao approved these changes

2022-03-10 08:12 UTC, merged