ASoC: SOF: mediatek: mt8195 change ipc timeout as 1 second
thesofproject/linux pull request #3524
Opened 2022-03-17 00:55 UTC by yaochunhung

Hi,
This PR is used to resolve ipc timeout for mt8195 during platform booting.
DSP ipc transmission is over than default 500ms during platform boot
flow then trigger exception. Check the time between DSP send ipc complete
notification via mailbox interrupt and linux receive and handle the irq
in the function "mt8195_dsp_handle_reply". Generally it takes more than
500ms but less than one second. Therefore adjust the ipc_timeout as 1
second to avoid the heavy loading of system to cause ipc timeout.
Please help to review it. Thanks.

2022-03-17 01:07 UTC, cujomalainey approved these changes, later dismissed

2022-03-17 01:34 UTC, ranj063 submitted a review, later dismissed

2022-03-17 12:05 UTC, ujfalusi requested changes
@yaochunhung, the commit message is really hard to follow.
It can be as simple as something like:
The IPC message sending can take longer than the default 500ms during system boot up due to the concurrent loading of different drivers.
Increase the IPC timeout to 1 second to avoid timeout errors due to Linux load and scheduling.

While at it, I would also instrument the system to see what blocks the boot for this long, there might be some misbehaving driver which can be fixed to have snappier bootup.

2022-03-17 15:14 UTC, yaochunhung commented
@ujfalusi Thanks for your suggestion. I have updated the commit message. please help to review it. thanks.

2022-03-17 20:39 UTC, cujomalainey approved these changes

2022-03-17 21:07 UTC, ranj063 approved these changes

2022-03-21 09:48 UTC, yaochunhung commented
SOFCI TEST

2022-03-21 12:10 UTC, ujfalusi approved these changes

2022-03-21 14:55 UTC, plbossart approved these changes

2022-03-21 14:55 UTC, merged