ASoC: codecs: add support for ES8326 dts
thesofproject/linux pull request #3546
Opened 2022-03-23 10:34 UTC by yangxiaohua2009

The ES8326 codec is not compatible with ES8316 and requires a dedicated driver.

This is a seperate patch for ES8326 dts

Codec patch in #3508 

Signed-off-by: David Yang <yangxiaohua@everest-semi.com>

2022-03-23 10:34 UTC, sofci commented
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

2022-03-23 15:16 UTC, plbossart requested changes

2022-03-23 15:16 UTC, plbossart commented on Documentation/devicetree/bindings/sound/everest,es8326.yaml
> +# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)
typo in commit message: separate.

2022-03-23 15:16 UTC, plbossart commented on Documentation/devicetree/bindings/sound/everest,es8326.yaml
> +  - Daniel Drake <drake@endlessm.com>
I don't think Daniel Drake is a maintainer for this codec.

2022-04-04 16:58 UTC, plbossart commented
closing, this will be handled with an upstream merge

2022-04-04 16:58 UTC, closed without merging