ASoC: SOF: ipc4-topology: Add the dai_config op
thesofproject/linux pull request #3547
Opened 2022-03-23 19:27 UTC by ranj063

Define and set the dai_config op for IPC4. Expose the
sof_ipc4_set_pipeline_state() as it is used by the dai_config op
implementation.

Co-developed-by: Rander Wang <rander.wang@linux.intel.com>
Signed-off-by: Rander Wang <rander.wang@linux.intel.com>
Co-developed-by: Bard Liao <yung-chuan.liao@linux.intel.com>
Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>
Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

2022-03-23 19:48 UTC, plbossart requested changes

2022-03-23 19:48 UTC, plbossart commented on sound/soc/sof/ipc4-topology.c
> +	case SOF_DAI_INTEL_SSP:
you would need to indicate if this is a 'TODO' which will be supported later or 'nothing to do here for DMIC/SSP'

2022-03-24 05:06 UTC, bardliao commented on sound/soc/sof/ipc4-topology.c
> +			 ipc4_copier->dai_type);
indentation?

2022-03-24 05:39 UTC, bardliao submitted a review, later dismissed

2022-03-24 14:02 UTC, bardliao submitted a review, later dismissed

2022-03-24 14:08 UTC, ujfalusi requested changes
@ranj063, the commit message tells that the `sof_ipc4_set_pipeline_state()` is going to be xposed by the commit, but it is not.

2022-03-24 14:08 UTC, ujfalusi commented on sound/soc/sof/ipc4-topology.c
> +		copier_data->gtw_cfg.node_id &= ~(0xFF);
Some people might ask for a define...

2022-03-24 14:52 UTC, ranj063 commented on sound/soc/sof/ipc4-topology.c
> +		copier_data->gtw_cfg.node_id &= ~(0xFF);
fixed now and the commit message

2022-03-24 14:54 UTC, ujfalusi submitted a review, later dismissed

2022-03-24 19:57 UTC, ranj063 commented on sound/soc/sof/ipc4-topology.c
> +		copier_data->gtw_cfg.node_id &= ~(0xFF);
fixed now (really) @ujfalusi

2022-03-25 00:50 UTC, bardliao approved these changes, later dismissed

2022-03-25 05:12 UTC, bardliao approved these changes

2022-03-25 13:09 UTC, ujfalusi approved these changes

2022-03-25 16:05 UTC, plbossart approved these changes

2022-03-25 16:06 UTC, merged