ASoC: SOF: amd: Add system suspend/resume callback for Renior
thesofproject/linux pull request #3605
Opened 2022-04-21 16:39 UTC by ajitkupandey

Add SOF PM ops callback in renior dsp ops to power off and on ACP
IP block during system suspend and resume on Renior platform.

Signed-off-by: Ajit Kumar Pandey <AjitKumar.Pandey@amd.com>

2022-04-21 18:01 UTC, plbossart requested changes

2022-04-21 18:01 UTC, plbossart commented on sound/soc/sof/amd/acp-dsp-offset.h
> +#define ACP_CONTROL				0x1004
commit message typo: Renoir.

2022-04-21 18:01 UTC, plbossart commented on sound/soc/sof/amd/pci-rn.c
> +	pm_runtime_allow(&pci->dev);
why is this needed?

we already configure pm_runtime stuff in sof_pci_probe_complete()

2022-04-21 18:01 UTC, plbossart commented on sound/soc/sof/amd/acp.c
> +	ret = acp_init(sdev);
you already write to ACP_CONTROL in acp_init(), see line 417. This looks suspicious to write to the same register before and after a call to acp_power_on(). You'd need to double-check if this is needed and explain with a comment if yes.

2022-04-22 15:44 UTC, plbossart approved these changes

2022-04-22 15:44 UTC, plbossart commented on sound/soc/sof/amd/acp.c
> +	return ret;
return acp_memory_init(sdev)?

2022-04-25 16:03 UTC, ranj063 commented on sound/soc/sof/amd/acp.h
> +int amd_sof_acp_resume(struct snd_sof_dev *sdev);
are there plans for this to be reused in other platforms? if not, maybe you can define these are static in renoir.c

2022-04-29 18:36 UTC, plbossart commented on sound/soc/sof/amd/acp.h
> +int amd_sof_acp_resume(struct snd_sof_dev *sdev);
@ajitkupandey ping?

2022-05-03 18:14 UTC, ajitkupandey commented on sound/soc/sof/amd/acp.h
> +int amd_sof_acp_resume(struct snd_sof_dev *sdev);
Yeah sure , moving and renaming this to renoir.c looks better as this callback may not be straight forward resused on other platforms. Thanks for suggestions ..I'll do that change and update this PR

2022-06-02 19:09 UTC, plbossart commented
Can we get an additional review from AMD folks? @bhiregou @sunilkumardommati

2022-06-03 02:29 UTC, sunilkumardommati approved these changes

2022-06-03 10:21 UTC, bhiregoudar approved these changes

2022-06-03 19:23 UTC, merged