ASoC: Intel: boards: rename RTL1019 comapatible driver to rt1019p
thesofproject/linux pull request #3677
Opened 2022-05-31 17:21 UTC by yongzhi1

Use rt1019p for rt1015p.c compatible codec and reserve the name rt1019
for 10EC1019 matched driver in sof_realtek_common.

Signed-off-by: Yong Zhi <yong.zhi@intel.com>

2022-05-31 17:23 UTC, yongzhi1 commented
There is no function change, the purpose is to avoid name conflicts when we add rt1019.c(10EC1019) support, thanks,

2022-05-31 21:25 UTC, plbossart requested changes
the rename is fine @yongzhi1 but you have a typo in your commit title (compatible)

2022-06-01 06:47 UTC, bardliao approved these changes, later dismissed

2022-06-01 17:22 UTC, plbossart requested changes
commit title still has a typo @yongzhi1 

ASoC: Intel: boards: rename RTL1019 comapatible driver to rt1019p
should be 

ASoC: Intel: boards: rename RTL1019 compatible driver to rt1019p

2022-06-01 19:56 UTC, yongzhi1 commented
> commit title still has a typo @yongzhi1
> 
> ASoC: Intel: boards: rename RTL1019 comapatible driver to rt1019p should be
> 
> ASoC: Intel: boards: rename RTL1019 compatible driver to rt1019p

ACK and thanks for review.

V2 Update:
- fix the typo in commit title line.

2022-06-01 20:22 UTC, plbossart approved these changes

2022-06-02 06:51 UTC, bardliao approved these changes

2022-06-02 14:19 UTC, merged