IPC4: TGL: Add multicore support
thesofproject/linux pull request #3711
Opened 2022-06-21 23:49 UTC by fredoh9

Currently This is based on Rander SRC PR, https://github.com/thesofproject/linux/pull/3692. Last two are additional changes for IPC4 TGL multicore support.

Tplg is I tested also based on Rander PR, https://github.com/thesofproject/sof/pull/5913. Set core_id 1 to SRC module. Topology graph is like this.

![cavs-sdw-src-gain](https://user-images.githubusercontent.com/45636982/174914499-16474b65-6565-4b14-a6fe-2f74276d1ad5.png)

2022-06-22 14:10 UTC, plbossart requested changes

2022-06-22 14:10 UTC, plbossart commented on sound/soc/sof/intel/tgl.c
> +	/* now send the iPC */
IPC

2022-06-22 14:10 UTC, plbossart commented on sound/soc/sof/intel/tgl.c
> +	/* now send the iPC */
IPC

2022-06-22 14:10 UTC, plbossart commented on sound/soc/sof/ipc4-topology.h
> -
spurious change.

2022-06-22 14:10 UTC, plbossart commented on sound/soc/sof/ipc4-priv.h
> +	u32 dx_mask;
this is very confusing, please describe more.

is core_mask the active cores, the managed cores? Why do we need a new definition?

Likewise Dx means 1 for D0 and 0 for D3? What about D0ix for core0?

2022-06-27 23:48 UTC, fredoh9 commented
Will merge this to https://github.com/thesofproject/linux/pull/3679

2022-06-27 23:48 UTC, closed without merging