ASoC: SOF: Intel: Fix kernel crash caused by surprisingly broken firmware
thesofproject/linux pull request #3714
Opened 2022-06-22 14:23 UTC by ujfalusi

Hi,

@kv2019i managed to 'craft' a firmware which for some unknown reasons sends a reply message before the FW_READY (it might not be the firmware, but the firmware causes this).
Since the reply_data is allocated after the first fw_ready message we will hit a NULL pointer in kernel, which is not a nice thing to do, even if the user loads broken binary to the DSP.

2022-06-22 14:37 UTC, plbossart requested changes

2022-06-22 14:37 UTC, plbossart commented on sound/soc/sof/intel/cnl.c
> +				struct sof_ipc4_msg *data = sdev->ipc->msg.reply_data;
Commit message typo in all  commits

the same condition ~~can~~ is present for IPC3.

2022-06-22 14:42 UTC, ujfalusi commented
Changes since v1:
- commit messages updated

2022-06-22 14:48 UTC, plbossart approved these changes, later dismissed

2022-06-22 15:26 UTC, ranj063 commented on sound/soc/sof/intel/cnl.c
> -			struct sof_ipc4_msg *data = sdev->ipc->msg.reply_data;
@ujfalusi just out of curiosity, why do we need the warning if we're going to ignore this anyway? I feel like this will come back to bite us later on

2022-06-22 15:35 UTC, ujfalusi commented on sound/soc/sof/intel/cnl.c
> -			struct sof_ipc4_msg *data = sdev->ipc->msg.reply_data;
@ranj063, we use it to print the warning as we need to know about this but not going to process it as a reply to avoid NULL pointer
We had similar issue with IMR boot, but since that bitten only after the first boot, we had the reply_data allocated already.

2022-06-22 16:01 UTC, ranj063 commented on sound/soc/sof/intel/cnl.c
> -			struct sof_ipc4_msg *data = sdev->ipc->msg.reply_data;
@ujfalusi if you have this warning and it so happens that we see it during first boot, what do we plan to do with it?

2022-06-22 16:19 UTC, kv2019i commented
Seems to be working. With the faulty FW, I now get this and no kernel panic anymore:

[   42.297904] sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x160]=0x140000 successful
[   42.297906] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware download successful, booting...
[   42.309633] sof-audio-pci-intel-tgl 0000:00:1f.3: IPC reply before FW_READY: 0x70000000|0x80
[   44.360377] sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[   44.360382] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware boot failure due to timeout
[   44.360383] sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)

2022-06-22 16:57 UTC, ujfalusi commented on sound/soc/sof/intel/cnl.c
> -			struct sof_ipc4_msg *data = sdev->ipc->msg.reply_data;
@ranj063, well, if we know that we have received `0x70000000|0x80` before fw_ready and then we have the dsp dump with ROM states, we might be able to figure out what is going on?

2022-06-22 18:23 UTC, ranj063 commented on sound/soc/sof/intel/cnl.c
> -			struct sof_ipc4_msg *data = sdev->ipc->msg.reply_data;
@ujfalusi i think we should downgrade this to a debug instead of warning. Anyway, if others are OK with a warning, you still have a typo in all your commit messages duplicated a "a a"

2022-06-22 18:30 UTC, kv2019i approved these changes, later dismissed
Thanks @ujfalusi ! I tried to attach the fault-inducing-fw, but github refused this, but drop me note if you want to try. I do think this must be fixed as the FW that causes this has an invalid signature (but not alone a sufficient condition to trigger the problem).

2022-06-23 01:46 UTC, RanderWang submitted a review, later dismissed
ROM could send ipc message to host. But in the log 0x70000000 | 0x80 is what ?

2022-06-23 06:15 UTC, ujfalusi commented
> ROM could send ipc message to host. But in the log 0x70000000 | 0x80 is what ?

@RanderWang, that is what puzzles me as well. if I decode it, it will be like
module message (bit 30)
it is reply (bit 29)
the message type is 0x10 which is not even defined.

Unless this is not an IPC message at all, but something else or decoded completely differently...

2022-06-23 06:18 UTC, ujfalusi commented
But according the the FSR code. the firmware is entered, so it must be something that the firmware is sending.
CSE decrypted the firmware even with a wrong key and we got something which apparently run or something and does not too sane thing?

2022-06-23 07:07 UTC, ujfalusi commented
Changes since v2:
- typo fixed in commit messages (double a)
- downgraded the prints to dev_dbg_ratelimited() since this issue should not happen on user's machine, only during development.

2022-06-23 13:37 UTC, ranj063 approved these changes

2022-06-23 13:38 UTC, plbossart approved these changes

2022-06-23 15:03 UTC, merged