fixup! ASoC: SOF: Intel: Add support for MeteorLake (MTL)
thesofproject/linux pull request #3744
Opened 2022-07-08 13:58 UTC by yongzhi1

Remove redundant CPA bit check after polling the same condition.

Signed-off-by: Yong Zhi <yong.zhi@intel.com>

2022-07-08 14:07 UTC, ujfalusi requested changes
@yongzhi1, this patch can not be a fixup as the original patch is already in linux-next:
064520e8aeaa2569f6504a50a37ac801b73656bc

2022-07-08 15:01 UTC, yongzhi1 commented
> @yongzhi1, this patch can not be a fixup as the original patch is already in linux-next: [064520e](https://github.com/thesofproject/linux/commit/064520e8aeaa2569f6504a50a37ac801b73656bc)

Ack, thanks, did not notice that.

2022-07-08 15:28 UTC, plbossart requested changes

2022-07-08 15:28 UTC, plbossart commented on sound/soc/sof/intel/mtl.c
> -	}
This cannot be a fixup @yongzhi1, the code is upstream already.

see commit 064520e8aeaa2569f6504a50a37ac801b73656bc

2022-07-11 02:08 UTC, bardliao commented
@yongzhi1 The change looks good to me. You can change the patch title and add a `Fixes:` tag in the commit message.

2022-07-12 05:18 UTC, aiChaoSONG approved these changes

2022-07-12 12:26 UTC, bardliao approved these changes

2022-07-12 15:20 UTC, plbossart approved these changes

2022-07-12 15:50 UTC, ranj063 approved these changes

2022-07-12 19:48 UTC, plbossart commented
@ujfalusi please review/merge if ok. I'd like to send this upstream this week.

2022-07-14 10:58 UTC, ujfalusi approved these changes

2022-07-14 10:59 UTC, merged