fixup! ASoC: SOF: Introduce struct snd_sof_pipeline
thesofproject/linux pull request #4037
Opened 2022-11-22 12:07 UTC by ujfalusi

With incorrect topology file we can end up with a case when swidget->spipe is NULL and it going to be caught in sof_widget_list_setup().

Check spipe agains NULL before dereferencing for the pipe_widget.

Reported-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>
Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

2022-11-22 12:07 UTC, ujfalusi commented
@singalsu, FYI

2022-11-22 12:27 UTC, singalsu approved these changes, later dismissed
This works, thanks Peter!

2022-11-22 12:49 UTC, lgirdwood requested changes
patch title is confusing, we are not introducing any struct but are checking a spipe before deref.

2022-11-22 13:48 UTC, ujfalusi commented
> patch title is confusing, we are not introducing any struct but are checking a spipe before deref.

@lgirdwood, it is a fixup for a patch only in topic/sof-dev, we use this method to squash patches down before sending things upstream, so we will have code which has gathered all fixes and bugfree.

2022-11-22 13:54 UTC, ujfalusi commented
Changes since v1:
- fix typo in commit message

2022-11-23 08:50 UTC, singalsu approved these changes

2022-11-23 10:36 UTC, iuliana-prodan approved these changes

2022-11-23 11:38 UTC, bardliao approved these changes

2022-11-23 12:54 UTC, ujfalusi commented
> patch title is confusing, we are not introducing any struct but are checking a spipe before deref.

@lgirdwood, can you revise your change request to clear the way for merging it without dismissing the block?

2022-11-24 03:02 UTC, keqiaozhang commented
SOFCI TEST

2022-11-24 03:11 UTC, keqiaozhang commented
SOFCI TEST

2022-11-24 10:22 UTC, lgirdwood approved these changes

2022-11-24 11:18 UTC, ujfalusi commented
Since this is fixing a NULL pointer dereference when a accidentally (or purposefully) crafted topology is in use, I'll merge this.
Earlier CI tests runs had green on the machines now marked as non tested.

2022-11-24 11:18 UTC, merged