fixup! ASoC: SOF: keep prepare/unprepare widgets in sink path
thesofproject/linux pull request #4061
Opened 2022-12-01 11:52 UTC by ujfalusi

On the prepare path if the widget_ops is NULL then none of the widget's prepared flag will be set, there is no need to iterate through as the function will do nothing.

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

2022-12-01 14:58 UTC, ranj063 approved these changes

2022-12-01 15:19 UTC, bardliao requested changes
@ujfalusi If we return here, we won't call `sof_prepare_widgets_in_path` at line 373 to prepare the sink widget. The sink widget can have widget_ops while the self widget doesn't.

2022-12-01 15:59 UTC, ranj063 commented
> @ujfalusi If we return here, we won't call `sof_prepare_widgets_in_path` at line 373 to prepare the sink widget. The sink widget can have widget_ops while the self widget doesn't.

Oh yes @bardliao is correct. we do need to continue to the rest of the widgets

2022-12-02 06:39 UTC, ujfalusi commented
> > @ujfalusi If we return here, we won't call `sof_prepare_widgets_in_path` at line 373 to prepare the sink widget. The sink widget can have widget_ops while the self widget doesn't.
> 
> Oh yes @bardliao is correct. we do need to continue to the rest of the widgets

That is true, but on the other hand that call to sof_prepare_widgets_in_path() will again going to do nothing as the `widget_ops` will be still NULL. 
If `widget_ops` is NULL then the `swidget->prepared` is not going to be set, ever. The whole call tree is going to be NOP with a running the CPU in a pointless loop.
Or do you see it differently?

2022-12-02 08:37 UTC, bardliao commented
> > > @ujfalusi If we return here, we won't call `sof_prepare_widgets_in_path` at line 373 to prepare the sink widget. The sink widget can have widget_ops while the self widget doesn't.
> > 
> > 
> > Oh yes @bardliao is correct. we do need to continue to the rest of the widgets
> 
> That is true, but on the other hand that call to sof_prepare_widgets_in_path() will again going to do nothing as the `widget_ops` will be still NULL. If `widget_ops` is NULL then the `swidget->prepared` is not going to be set, ever. The whole call tree is going to be NOP with running the CPU in a pointless loop. Or do you see it differently?

Ok, I got your point now. All widgets will use the same IPC type, if one widget doesn't have widget_ops, then none of widgets will have widget_ops.

2022-12-02 08:37 UTC, bardliao approved these changes

2022-12-02 19:24 UTC, plbossart approved these changes

2022-12-02 19:25 UTC, merged