Add support for rt1019_rt5682 for RPL
thesofproject/linux pull request #4403
Opened 2023-06-01 07:08 UTC by terry182

Boards were using this in older kernels before adl and rpl ids were split. Add this back to maintain support.

2023-06-01 14:40 UTC, plbossart requested changes
nit-pick below

2023-06-01 14:40 UTC, plbossart commented on sound/soc/intel/boards/sof_rt5682.c
> +	},
can you move this up to line 1122 to keep all RPL descriptor together? Thanks!

2023-06-01 17:10 UTC, terry182 commented on sound/soc/intel/boards/sof_rt5682.c
> +	},
No problem at all. I wonder should I submit another patch to re-order things, as I saw some JSL and TGL scattered.

2023-06-01 17:27 UTC, plbossart commented on sound/soc/intel/boards/sof_rt5682.c
> +	},
that would be great @terry182, this file is a bit of a mess. Thanks!

2023-06-01 17:59 UTC, cujomalainey approved these changes

2023-06-02 15:31 UTC, plbossart approved these changes

2023-06-02 15:31 UTC, merged