Refactor ACP <-> PSP communication for AMD platfroms
thesofproject/linux pull request #4424
Opened 2023-06-13 12:22 UTC by mkatraga

2023-06-13 12:23 UTC, sofci commented
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

2023-06-13 12:23 UTC, vijendarmukunda commented
test this please

2023-06-14 13:42 UTC, bhiregoudar submitted a review, later dismissed

2023-06-15 05:25 UTC, sunilkumardommati submitted a review, later dismissed

2023-06-15 05:48 UTC, vijendarmukunda approved these changes, later dismissed

2023-06-15 07:45 UTC, plbossart requested changes

2023-06-15 07:45 UTC, plbossart commented on sound/soc/sof/amd/acp.c
> +	const struct sof_amd_acp_desc *desc = get_chip_info(sdev->pdata);
typo in commit title: compleiton

2023-06-15 07:45 UTC, plbossart commented on sound/soc/sof/amd/acp.c
> +	if (desc->rev == 3) {
consider using macros or add a commit to explain magic numbers in code.

2023-06-15 11:56 UTC, mkatraga commented on sound/soc/sof/amd/acp.c
> +	const struct sof_amd_acp_desc *desc = get_chip_info(sdev->pdata);
will fix it.

2023-06-15 11:56 UTC, mkatraga commented on sound/soc/sof/amd/acp.c
> +	if (desc->rev == 3) {
will add comment.

2023-06-15 12:27 UTC, plbossart commented on sound/soc/sof/amd/acp.c
> +	if (desc->rev == 3) {
it's renoir, not renior....

2023-06-15 16:08 UTC, plbossart commented on sound/soc/sof/amd/acp.h
> +#define ACP_PSP_TIMEOUT				1000000
units? US, NS?

2023-06-15 16:30 UTC, mkatraga commented on sound/soc/sof/amd/acp.h
> +#define ACP_PSP_TIMEOUT				1000000
that's US, its a miss will updates as  ACP_PSP_TIMEOUT_US.

2023-06-16 08:09 UTC, plbossart approved these changes

2023-06-16 08:09 UTC, plbossart commented
test this please

2023-06-16 10:22 UTC, vijendarmukunda approved these changes

2023-06-20 11:26 UTC, sunilkumardommati approved these changes

2023-06-20 13:20 UTC, bhiregoudar approved these changes

2023-06-22 11:33 UTC, mkatraga commented
Hi,

@plbossart Can you please help to merge these patches.

2023-06-29 09:23 UTC, merged