ASoC: Intel: sof_maxim_common: check return value
thesofproject/linux pull request #4695
Opened 2023-11-09 05:10 UTC by bardliao

snd_soc_dai_set_tdm_slot() could return error, and add an else to clarify that `if (!strcmp(codec_dai->component->name, MAX_98373_DEV0_NAME))` and `if (!strcmp(codec_dai->component->name, MAX_98373_DEV1_NAME))` can't be true at the same time.

2023-11-09 06:15 UTC, brentlu submitted a review, later dismissed

2023-11-09 06:46 UTC, aiChaoSONG submitted a review, later dismissed

2023-11-10 01:13 UTC, plbossart approved these changes

2023-11-10 01:14 UTC, plbossart commented
````
ERROR: else should follow close brace '}'
#24: FILE: sound/soc/intel/boards/sof_maxim_common.c:71:
 		}
+		else if (!strcmp(codec_dai->component->name, MAX_98373_DEV1_NAME)) {
````

2023-11-10 01:14 UTC, plbossart requested changes
checkpatch style

2023-11-10 05:09 UTC, bardliao commented
> checkpatch style

Fixed

2023-11-10 06:37 UTC, aiChaoSONG approved these changes

2023-11-10 16:30 UTC, plbossart approved these changes

2023-11-10 16:33 UTC, merged