ALSA: hda/realtek: Add "Intel Reference board" SSID in the ALC256.
thesofproject/linux pull request #4725
Opened 2023-12-01 19:28 UTC by syedk008

Add "Intel Reference boad" SSID in the alc256.
Enable "power saving mode" and Enable "headset jack mode".

2023-12-01 19:29 UTC, sofci commented
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

2023-12-01 20:47 UTC, plbossart requested changes

2023-12-01 20:47 UTC, plbossart commented on sound/pci/hda/patch_realtek.c
> +	SND_PCI_QUIRK(0x10ec, 0x12f6, "Intel Reference board", ALC295_FIXUP_CHROME_BOOK),
commit message: s/boad/board

2023-12-06 16:00 UTC, plbossart approved these changes

2023-12-06 16:01 UTC, plbossart commented
test this please

2023-12-07 13:09 UTC, ujfalusi approved these changes

2023-12-18 13:31 UTC, merged