Add stub for sof_ssp_get_codec_name
thesofproject/linux pull request #4746
Opened 2023-12-13 13:59 UTC by charleskeepax

Currently the sof_sdw stuff wont build without ssp_common, which is not selected or required by it.

Not sure this is the preferred way to handle this, other ways might be to select SSP_COMMON from sof_sdw, or to move the whole function to somewhere more guaranteed to be built in. Also not sure if we want to return NULL, kernel should handle that fine but might be nicer to return like "unavailable" or something. But open to comments, or alternative patches.

2023-12-13 14:22 UTC, bardliao approved these changes, later dismissed

2023-12-13 14:40 UTC, charleskeepax commented
Apologies for the edit after your review, just noticed some stale function prototypes that needed removed as well, might as well add them into this pull request.

2023-12-14 00:49 UTC, bardliao approved these changes
Thanks @charleskeepax

2023-12-18 12:35 UTC, plbossart requested changes
the Fixes: c052a47 tag is not quite right, this isn't a commit that's upstream

2023-12-19 10:25 UTC, charleskeepax commented
Yeah apologies, not sure what I was thinking there that commit isn't upstream so shouldn't get a fixes tag. Will push a version without it shortly.

2023-12-19 10:39 UTC, plbossart approved these changes

2023-12-19 11:00 UTC, ujfalusi approved these changes

2023-12-20 01:50 UTC, bardliao commented
https://sof-ci.01.org/linuxpr/PR4746/build832/devicetest/index.html?model=TGLU_RVP_NOCODEC-ipc4&testcase=check-suspend-resume-with-playback is a known issue (https://github.com/thesofproject/sof/issues/8641). Not related to this PR. Merge it now.

2023-12-20 01:50 UTC, merged