AMD SOF based generic SoundWire machine driver
thesofproject/linux pull request #5017
Opened 2024-05-27 08:47 UTC by vijendarmukunda

This patch series includes below listed changes.
1) Move and rename Common helper functions in Intel machine driver to common place holder which can be made generic.
2) Move and rename Codec helper functions which can be made generic.
3) Move the common Codec info list which is generic
4) Add pci revision id field in mach_params for platform distinguish 
5) AMD SOF based SoundWire machine generic driver.

2024-05-28 13:10 UTC, plbossart requested changes
I am having second thoughts on the incremental renames, which contains omissions.
It might be just easier to rename everything in sof_sdw, then do the code moves.

Also the PS stuff is badly broken, a sleep as the first step in a probe isn't going to fly.

2024-05-28 13:10 UTC, plbossart commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +#endif
maybe move to include/sound/ ?

2024-05-28 13:10 UTC, plbossart commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +struct sof_sdw_codec_info {
rename as soc_sdw_codec_info ?

2024-05-28 13:10 UTC, plbossart commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +struct sof_sdw_dai_info {
rename as sof_sdw_dai_info?

2024-05-28 13:10 UTC, plbossart commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +#define SOF_SDW_MAX_DAI_NUM             8
Rename macro 'SOF_SDW_MAX_DAI_NUM' as 'SOC_SDW_MAX_DAI_NUM'.

that seems to be missed?

2024-05-28 13:10 UTC, plbossart commented on sound/soc/amd/ps/ps-sdw-mach.c
> +};
why can't you use the functions you added earlier, e.g.

````c
static const struct snd_soc_ops acp63_sdw_ops = {
	.startup = asoc_sdw_startup,
	.prepare = asoc_sdw_prepare,
	.trigger = asoc_sdw_trigger,
	.hw_params = asoc_sdw_hw_params,
	.hw_free = asoc_sdw_hw_free,
	.shutdown = asoc_sdw_shutdown,
};
````

2024-05-28 13:10 UTC, plbossart commented on sound/soc/amd/ps/ps-sdw-mach.c
> +	usleep_range(200 * 1000, 250 * 1000);
oh that seems so suspicious right there....

That's a NAK from me, there shouldn't be any hard-coded sleep time in a probe, that's a clear sign of something fishy.

2024-05-28 13:10 UTC, plbossart commented on sound/soc/amd/ps/ps-sdw-mach.c
> +MODULE_ALIAS("platform:" DRV_NAME);
and what does this have to do with "ASoC: intel/sdw_utils: move rtk jack common helper functions" anyways, that's a patch split or git squash that didn't go well.

2024-05-28 13:10 UTC, plbossart commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +#define MAX_NO_PROPS 2
SOC_SDW prefix

2024-05-28 13:10 UTC, plbossart commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +	struct asoc_sdw_dai_info dais[SOF_SDW_MAX_DAI_NUM];
this rename should have been done earlier IMHO

2024-05-28 13:10 UTC, plbossart commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +	struct asoc_sdw_dai_info dais[SOF_SDW_MAX_DAI_NUM];
and you still have SOF_SDW in the define for the size.

2024-05-28 13:10 UTC, plbossart commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +
Now that I think about it, it's probably easier to do the renames in one shot

a) rename everything in sof_sdw. It'll be massively different but that's just a rename.
b) move code in the utils stuff.
c) add new things.

That will reduce the scope for errors/omissions.

2024-05-28 15:29 UTC, vijendarmukunda commented on sound/soc/amd/ps/ps-sdw-mach.c
> +};
It's my bad. It shouldn't be included in this patch.  This is a just test version machine driver file for PS platform. 
We already working on implementing legacy machine driver similar to sof based soundwire generic machine driver.
Will drop these changes

2024-05-28 15:31 UTC, vijendarmukunda commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +struct sof_sdw_dai_info {
We have renamed in it later patch.

2024-05-28 15:31 UTC, vijendarmukunda commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +struct sof_sdw_codec_info {
already renamed in later patch.

2024-05-28 15:32 UTC, vijendarmukunda commented on sound/soc/amd/ps/ps-sdw-mach.c
> +MODULE_ALIAS("platform:" DRV_NAME);
Please ignore this file changes. Will drop this file.

2024-05-28 15:32 UTC, vijendarmukunda commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +#define MAX_NO_PROPS 2
will fix it.

2024-05-28 15:33 UTC, vijendarmukunda commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +	struct asoc_sdw_dai_info dais[SOF_SDW_MAX_DAI_NUM];
In later patch we redefined the macro.

2024-05-28 15:34 UTC, vijendarmukunda commented on sound/soc/sdw_utils/soc_sdw_utils.h
> +
Agreed. will make the changes.

2024-05-28 15:36 UTC, vijendarmukunda commented on sound/soc/amd/ps/ps-sdw-mach.c
> +	usleep_range(200 * 1000, 250 * 1000);
Sorry this is a test version file added by mistake. We are working on implementing Soundwire generic machine driver for legacy(NO DSP) stack in similar to SOF based Soundwire generic machine driver. This file will be dropped.

2024-05-28 15:38 UTC, vijendarmukunda commented
Removed ps-sdw-mach.c file and rebased the patch series and posted V2 series.
Will post the V3 patch series after fixing the review comments and also will resolve the merge conflict in sof_sdw.c file.

2024-05-29 06:26 UTC, vijendarmukunda commented
Requires patches rebase to resolve the merge conflict and needs to redefine the patch series.will open the new PR with fresh patch series

2024-05-29 06:26 UTC, closed without merging