ASoC: Intel: sof_sdw: fix jack detection on ADL-N variant RVP
thesofproject/linux pull request #5044
Opened 2024-06-06 14:50 UTC by plbossart

Experimental tests show that JD2_100K is required, otherwise the jack is detected always even with nothing plugged-in.

To avoid matching with other known quirks the SKU information is used.

2024-06-06 15:07 UTC, ujfalusi approved these changes

2024-06-06 15:08 UTC, ujfalusi requested changes
@plbossart, this does not compile?

2024-06-07 05:19 UTC, ujfalusi approved these changes

2024-06-07 05:43 UTC, bardliao approved these changes

2024-06-07 12:07 UTC, ssavati commented
@plbossart tested on ADL-N variant. JD works fine.

2024-06-10 07:32 UTC, merged