ASoC: SOF: Intel: hda-pcm: Limit the maximum number of periods by MAX…
thesofproject/linux pull request #5045
Opened 2024-06-06 15:00 UTC by ujfalusi

…_BDL_ENTRIES

The number of periods for HDA is limited by the maximum number of BDL entries we have space for (which is 255).

Make sure that we don't allow more periods than the maximum number of BDL entries minus one.

2024-06-06 15:15 UTC, plbossart requested changes

2024-06-06 15:15 UTC, plbossart commented on sound/soc/sof/intel/hda-pcm.c
> +	/* Limit the maximum number of periods to not exceed the BDL etries count */
typo: entries

2024-06-06 15:15 UTC, plbossart commented on sound/soc/sof/intel/hda-pcm.c
> +
The spec says up to 256 entries are legit, this should be MAX_BDL_ENTRIES, not a MAX_BDL_ENTRIES - 1


commit message suggested edit:

The HDaudio specification Section 3.6.2 limits the number of BDL entries to 256.

Make sure we don't allow more periods than this normative value.

2024-06-07 05:36 UTC, ujfalusi commented
Changes since v1:
- fixed off by one for the maximum number of period
- fixed the typo in comment and updated the commit message

Note: When sending for upstream, we should mark it for stable backport, I'll test the oldest I can find where it applies.

2024-06-07 06:53 UTC, ujfalusi commented
Interesting, legacy HDA (and AVS, skl) is using 32 as periods_max (AZX_MAX_FRAG)...

2024-06-07 07:39 UTC, plbossart commented
> Interesting, legacy HDA (and AVS, skl) is using 32 as periods_max (AZX_MAX_FRAG)...

hda_register.h:#define BDL_SIZE         4096
hda_register.h:#define AZX_MAX_BDL_ENTRIES      (BDL_SIZE / 16)

2024-06-07 07:47 UTC, plbossart commented
I was trying to find the explanation for this comment 

````c
/* max number of fragments - we may use more if allocating more pages for BDL */
````

That comment is older than 2.6.12-rc2 and git history. We may need to ask @tiwai why there's a restriction to 32 periods?

2024-06-07 08:04 UTC, ujfalusi commented
> I was trying to find the explanation for this comment
> 
> ```c
> /* max number of fragments - we may use more if allocating more pages for BDL */
> ```
> 
> That comment is older than 2.6.12-rc2 and git history. We may need to ask @tiwai why there's a restriction to 32 periods?

Headroom to handle non continuous ALSA buffers perhaps?

2024-06-07 15:56 UTC, yongzhi1 approved these changes

2024-06-14 08:24 UTC, plbossart approved these changes

2024-06-14 08:25 UTC, merged