Remove common_hdmi_codec_drv variable
thesofproject/linux pull request #5158
Opened 2024-08-23 16:40 UTC by brentlu

Remove common_hdmi_codec_drv variable from snd_soc_acpi_mach_params structure and SOF machine drivers since we don't need it anymore.

2024-08-26 06:02 UTC, ujfalusi approved these changes

2024-08-26 07:34 UTC, bardliao approved these changes

2024-08-26 07:38 UTC, bardliao commented
Some failures on LNLM_RVP_HDA https://sof-ci.01.org/linuxpr/PR5158/build4423/devicetest/index.html. @brentlu FYI

2024-08-26 07:38 UTC, bardliao commented
SOFCI TEST

2024-08-26 07:39 UTC, bardliao requested changes
Let's wait for CI test result

2024-08-27 01:16 UTC, bardliao approved these changes
CI test result looks good

2024-08-27 01:16 UTC, merged