AMD SOF Soundwire generic machine driver code refactor
thesofproject/linux pull request #5171
Opened 2024-09-10 08:14 UTC by vijendarmukunda

2024-09-10 08:39 UTC, plbossart submitted a review, later dismissed
looks ok to me but @charleskeepax and @bardliao must review

2024-09-10 09:11 UTC, vijendarmukunda commented
@plbossart @bardliao @charleskeepax : could you please review ?

2024-09-11 09:50 UTC, charleskeepax commented on sound/soc/sdw_utils/soc_sdw_utils.c
> +static const char * const type_strings[] = {"SimpleJack", "SmartAmp", "SmartMic"};
This is only used in the debug statement below, I would be tempted to drop it and just print out the number directly. The trouble with having the strings here is there ends up being an expectation that this array, the array in the AMD stuff, and the array in the Intel stuff all match. Simpler to just avoid the problem and allow Intel/AMD to have control over what names are used on their systems. Either that or if we do want to make them all the same export the array and share it, but I think I prefer the former.

2024-09-11 09:50 UTC, charleskeepax requested changes
Mostly looks good one very minor comment from me.

2024-09-11 10:04 UTC, vijendarmukunda commented on sound/soc/sdw_utils/soc_sdw_utils.c
> +static const char * const type_strings[] = {"SimpleJack", "SmartAmp", "SmartMic"};
Will drop type_strings from the debug statement in asoc_sdw_parse_sdw_endpoints() function and will append AMD tag for type_strings used in AMD machine driver code.

2024-09-11 11:37 UTC, vijendarmukunda commented
@charleskeepax : dropped type strings from debug statement. There is no hard requirement to change type_strings in AMD code as of now. Changing the type_strings in driver code, also require changes in topology file. For current platform , we want to go with no modifications in type_strings for AMD source code.

2024-09-11 11:38 UTC, vijendarmukunda commented
@bardliao : please review the PR

2024-09-11 12:01 UTC, charleskeepax approved these changes
Yeah no need to change the strings. But this way there is less coupling between the two drivers. Anyways all looks good to me.

2024-09-11 12:34 UTC, bardliao approved these changes
LGTM

2024-09-12 07:02 UTC, vijendarmukunda commented
@bardliao @plbossart : as PR got approved could you please merge the PR? we have other patches to be submitted on top of it?

2024-09-12 10:37 UTC, merged